---
title: "manure_surplus_code_submission"
author: "yanyu wang"
date: "2025-01-03"
output: html_document
---

```{r}
library(ggplot2)
library(raster)
library(dplyr)
library(sf)
library(tmap)
library(tmaptools)
tmap_mode("plot")
library(RColorBrewer)
library(cluster)
library(factoextra)
library(gridExtra)
library(writexl)
library(openxlsx)
library(readxl)
library(writexl)
library(waterfalls)
library(ggthemes)
```


## national level waterfall charts (manure surplus)
```{r}
df3 <- read.csv("~/Desktop/revised manure sur/waterfall11062024.csv")

waterfall(df3, fill_by_sign = FALSE, fill_colours = c("#D2B48C", "#CC9900", "#996600", "#009933"),calc_total = TRUE, total_rect_color = "#FDF5E6", total_rect_text_color = "black", rect_text_size = 2, total_axis_text = "Outcome") + 
  labs(title="", 
         x="", y = expression(Manure~Surplus ~ "("*Tg~N ~ yr^-1*")"), 
         
         
         ) +
  theme_bw() +
    theme( 
         axis.text.y = element_text(size = 15),
        axis.title.y  = element_text(size = 15),
       axis.text.x = element_text(size = 15)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(-15, 1))
```

## national level waterfall charts (synthetic fertilizer use)
```{r}
df4 <- read.csv("~/Desktop/revised manure sur/waterfall11062024fer.csv")

waterfall(df4, fill_by_sign = FALSE, fill_colours = c("#D2B48C", "#CC9900", "#996600", "#009933"),calc_total = TRUE, total_rect_color = "#FDF5E6", total_rect_text_color = "black", rect_text_size = 2, total_axis_text = "Outcome" ) + 
  labs(title="", 
         x="", y = expression(Synthetic~fertilizer~use~ "("*Tg~N ~ yr^-1*")")) +
  theme_bw() +
    theme( 
         axis.text.y = element_text(size = 15),
        axis.title.y  = element_text(size = 15),
       axis.text.x = element_text(size = 15) ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(0, 13))

```

## county-level analyses 
```{r}
beef17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/cattle_onfeed_sales.csv")

beef17_sales <- beef17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

beef17_sales$State.ANSI[1:95] <- paste0("0", beef17_sales$State.ANSI[1:95])

beef17_sales <- beef17_sales %>%
    arrange(beef17_sales$County.ANSI, decreasing = FALSE)

beef17_sales$County.ANSI[1:143]<- paste0("00", beef17_sales$County.ANSI[1:143])

beef17_sales$County.ANSI[144:1214]<- paste0("0", beef17_sales$County.ANSI[144:1214])

beef17_sales$GEOID <- paste(beef17_sales$State.ANSI, beef17_sales$County.ANSI, sep = "")

beef17_sales$Value<- as.numeric(as.character(beef17_sales$Value))

beef17_sales$Value[is.na(beef17_sales$Value)] <- 0

beef17_sales <- beef17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)
```

```{r}
beef17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/cattle_onfeed_inven.csv")

beef17_inven <- beef17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

beef17_inven$State.ANSI[1:66] <- paste0("0", beef17_inven$State.ANSI[1:66])

beef17_inven <- beef17_inven %>%
    arrange(beef17_inven$County.ANSI, decreasing = FALSE)

beef17_inven$County.ANSI[1:122]<- paste0("00", beef17_inven$County.ANSI[1:122])

beef17_inven$County.ANSI[123:1034]<- paste0("0", beef17_inven$County.ANSI[123:1034])

beef17_inven$GEOID <- paste(beef17_inven$State.ANSI, beef17_inven$County.ANSI, sep = "")

beef17_inven$Value<- as.numeric(as.character(beef17_inven$Value))

beef17_inven$Value[is.na(beef17_inven$Value)] <- 0

beef17_inven <- beef17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(beef17_inven$inventory)
```


```{r}
beef <- merge(beef17_inven, beef17_sales, by = "GEOID", all = TRUE)
beef[is.na(beef)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
beef <- beef %>%
  mutate(man_beef = (((inventory*1/2.5)+(sales/2.5*(2.5-1)/2.5))*(1/1.02))*58.3362/10^9) %>%
  dplyr::select(GEOID, man_beef)

sum(beef$man_beef)

str(beef)
```



```{r}
milk17 <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/milk_inven.csv")

milk17 <- milk17 %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

milk17$State.ANSI[1:215] <- paste0("0", milk17$State.ANSI[1:215])

milk17 <- milk17 %>%
    arrange(milk17$County.ANSI, decreasing = FALSE)

milk17$County.ANSI[1:198]<- paste0("00", milk17$County.ANSI[1:198])

milk17$County.ANSI[199:1546]<- paste0("0", milk17$County.ANSI[199:1546])

milk17$GEOID <- paste(milk17$State.ANSI, milk17$County.ANSI, sep = "")

milk17$Value<- as.numeric(as.character(milk17$Value))

milk17$Value[is.na(milk17$Value)] <- 0

milk17 <- milk17 %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)


milk17 <- milk17 %>%
  mutate(man_milk =inventory*(1/0.73)*118.25676/10^9) %>%
  dplyr::select(GEOID, man_milk)

sum(milk17$man_milk)

cattle<- merge(beef, milk17, by = "GEOID", all = TRUE)
```

```{r}
hog17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/hogs_inven_2012.csv")

hog17_inven <- hog17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

hog17_inven$State.ANSI[1:248] <- paste0("0", hog17_inven$State.ANSI[1:248])

hog17_inven <- hog17_inven %>%
    arrange(hog17_inven$County.ANSI, decreasing = FALSE)

hog17_inven$County.ANSI[1:215]<- paste0("00", hog17_inven$County.ANSI[1:215])

hog17_inven$County.ANSI[216:1657]<- paste0("0", hog17_inven$County.ANSI[216:1657])

hog17_inven$GEOID <- paste(hog17_inven$State.ANSI, hog17_inven$County.ANSI, sep = "")

hog17_inven$Value<- as.numeric(as.character(hog17_inven$Value))

hog17_inven$Value[is.na(hog17_inven$Value)] <- 0

hog17_inven <- hog17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(hog17_inven$inventory)
```

```{r}
hog17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/hog_sales.csv")

hog17_sales <- hog17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

hog17_sales$State.ANSI[1:257] <- paste0("0", hog17_sales$State.ANSI[1:257])

hog17_sales <- hog17_sales %>%
    arrange(hog17_sales$County.ANSI, decreasing = FALSE)

hog17_sales$County.ANSI[1:223]<- paste0("00", hog17_sales$County.ANSI[1:223])

hog17_sales$County.ANSI[224:1759]<- paste0("0", hog17_sales$County.ANSI[224:1759])

hog17_sales$GEOID <- paste(hog17_sales$State.ANSI, hog17_sales$County.ANSI, sep = "")

hog17_sales$Value<- as.numeric(as.character(hog17_sales$Value))

hog17_sales$Value[is.na(hog17_sales$Value)] <- 0

hog17_sales <- hog17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(hog17_sales$sales)
```

```{r}
hog <- merge(hog17_inven, hog17_sales, by = "GEOID", all = TRUE)
hog[is.na(hog)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
hog <- hog %>%
  mutate(man_hog = ( inventory*(1/2.27)*32.39298 + ((sales/2*(2-1)/2))*(1/7.4)*108.43875)/10^9  ) %>%
  mutate(manhog_inven = inventory*(1/2.27)*32.39298/10^9) %>%
  mutate(manhog_sales = (sales/2*(2-1)/2)*(1/7.4)*108.43875/10^9) %>%
  dplyr::select(GEOID, man_hog, manhog_inven, manhog_sales)

sum(hog$man_hog)

sum(hog$manhog_inven)

sum(hog$manhog_sales)

```


```{r}
broiler17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/broiler_inven.csv")

broiler17_inven <- broiler17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

broiler17_inven$State.ANSI[1:250] <- paste0("0", broiler17_inven$State.ANSI[1:250])

broiler17_inven <- broiler17_inven %>%
    arrange(broiler17_inven$County.ANSI, decreasing = FALSE)

broiler17_inven$County.ANSI[1:210]<- paste0("00", broiler17_inven$County.ANSI[1:210])

broiler17_inven$County.ANSI[211:1643]<- paste0("0", broiler17_inven$County.ANSI[211:1643])

broiler17_inven$GEOID <- paste(broiler17_inven$State.ANSI, broiler17_inven$County.ANSI, sep = "")

broiler17_inven$Value<- as.numeric(as.character(broiler17_inven$Value))

broiler17_inven$Value[is.na(broiler17_inven$Value)] <- 0

broiler17_inven <- broiler17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(broiler17_inven$inventory)
```


```{r}
broiler17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/broiler_sales.csv")

broiler17_sales <- broiler17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

broiler17_sales$State.ANSI[1:226] <- paste0("0", broiler17_sales$State.ANSI[1:226])

broiler17_sales <- broiler17_sales %>%
    arrange(broiler17_sales$County.ANSI, decreasing = FALSE)

broiler17_sales$County.ANSI[1:186]<- paste0("00", broiler17_sales$County.ANSI[1:186])

broiler17_sales$County.ANSI[187:1448]<- paste0("0", broiler17_sales$County.ANSI[187:1448])

broiler17_sales$GEOID <- paste(broiler17_sales$State.ANSI, broiler17_sales$County.ANSI, sep = "")

broiler17_sales$Value<- as.numeric(as.character(broiler17_sales$Value))

broiler17_sales$Value[is.na(broiler17_sales$Value)] <- 0

broiler17_sales <- broiler17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(broiler17_sales$sales)
```

```{r}
broiler <- merge(broiler17_inven, broiler17_sales, by = "GEOID", all = TRUE)
broiler[is.na(broiler)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
broiler <- broiler %>%
  mutate(man_broiler = (((inventory*1/6)+(sales/6*(6-1)/6))*(1/382)*157.168755/10^9) ) %>%
  dplyr::select(GEOID, man_broiler)

sum(broiler$man_broiler)
```

```{r}
layer17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/layer_inven.csv")

layer17_inven <- layer17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

layer17_inven$State.ANSI[1:283] <- paste0("0", layer17_inven$State.ANSI[1:283])

layer17_inven <- layer17_inven %>%
    arrange(layer17_inven$County.ANSI, decreasing = FALSE)

layer17_inven$County.ANSI[1:236]<- paste0("00", layer17_inven$County.ANSI[1:236])

layer17_inven$County.ANSI[237:1868]<- paste0("0", layer17_inven$County.ANSI[237:1868])

layer17_inven$GEOID <- paste(layer17_inven$State.ANSI, layer17_inven$County.ANSI, sep = "")

layer17_inven$Value<- as.numeric(as.character(layer17_inven$Value))

layer17_inven$Value[is.na(layer17_inven$Value)] <- 0

layer17_inven <- layer17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(layer17_inven$inventory)
```

```{r}
layer17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/layer_sales.csv")

layer17_sales <- layer17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

layer17_sales$State.ANSI[1:253] <- paste0("0", layer17_sales$State.ANSI[1:253])

layer17_sales <- layer17_sales %>%
    arrange(layer17_sales$County.ANSI, decreasing = FALSE)

layer17_sales$County.ANSI[1:210]<- paste0("00", layer17_sales$County.ANSI[1:210])

layer17_sales$County.ANSI[211:1629]<- paste0("0", layer17_sales$County.ANSI[211:1629])

layer17_sales$GEOID <- paste(layer17_sales$State.ANSI, layer17_sales$County.ANSI, sep = "")

layer17_sales$Value<- as.numeric(as.character(layer17_sales$Value))

layer17_sales$Value[is.na(layer17_sales$Value)] <- 0

layer17_sales <- layer17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(layer17_sales$sales)
```


```{r}
layer <- merge(layer17_inven, layer17_sales, by = "GEOID", all = TRUE)
layer[is.na(layer)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
layer <- layer %>%
  mutate(man_layer = (inventory+sales)*(1/293)*189.489735/10^9 ) %>%
  dplyr::select(GEOID, man_layer)

sum(layer$man_layer)
```


```{r}
pullet17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/pullet_inven.csv")

pullet17_inven <- pullet17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

pullet17_inven$State.ANSI[1:247] <- paste0("0", pullet17_inven$State.ANSI[1:247])

pullet17_inven <- pullet17_inven %>%
    arrange(pullet17_inven$County.ANSI, decreasing = FALSE)

pullet17_inven$County.ANSI[1:216]<- paste0("00", pullet17_inven$County.ANSI[1:216])

pullet17_inven$County.ANSI[217:1639]<- paste0("0", pullet17_inven$County.ANSI[217:1639])

pullet17_inven$GEOID <- paste(pullet17_inven$State.ANSI, pullet17_inven$County.ANSI, sep = "")

pullet17_inven$Value<- as.numeric(as.character(pullet17_inven$Value))

pullet17_inven$Value[is.na(pullet17_inven$Value)] <- 0

pullet17_inven <- pullet17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(pullet17_inven$inventory)
```


```{r}
pullet17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/pullet_sales.csv")

pullet17_sales <- pullet17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

pullet17_sales$State.ANSI[1:147] <- paste0("0", pullet17_sales$State.ANSI[1:147])

pullet17_sales <- pullet17_sales %>%
    arrange(pullet17_sales$County.ANSI, decreasing = FALSE)

pullet17_sales$County.ANSI[1:101]<- paste0("00", pullet17_sales$County.ANSI[1:101])

pullet17_sales$County.ANSI[102:815]<- paste0("0", pullet17_sales$County.ANSI[102:815])

pullet17_sales$GEOID <- paste(pullet17_sales$State.ANSI, pullet17_sales$County.ANSI, sep = "")

pullet17_sales$Value<- as.numeric(as.character(pullet17_sales$Value))

pullet17_sales$Value[is.na(pullet17_sales$Value)] <- 0

pullet17_sales <- pullet17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(pullet17_sales$sales)
```

```{r}
pullet <- merge(pullet17_inven, pullet17_sales, by = "GEOID", all = TRUE)
pullet[is.na(pullet)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
pullet <- pullet %>%
  mutate(man_pullet  = (((inventory*1/2.25)+(sales/2.25*(2.25-1)/2.25))*(1/350))/10^9*100.453455) %>%
  dplyr::select(GEOID, man_pullet)

sum(pullet$man_pullet)
```


```{r}
turkey17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/turkey_inven.csv")

turkey17_inven <- turkey17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

turkey17_inven$State.ANSI[1:219] <- paste0("0", turkey17_inven$State.ANSI[1:219])

turkey17_inven <- turkey17_inven %>%
    arrange(turkey17_inven$County.ANSI, decreasing = FALSE)

turkey17_inven$County.ANSI[1:195]<- paste0("00", turkey17_inven$County.ANSI[1:195])

turkey17_inven$County.ANSI[196:1475]<- paste0("0", turkey17_inven$County.ANSI[196:1475])

turkey17_inven$GEOID <- paste(turkey17_inven$State.ANSI, turkey17_inven$County.ANSI, sep = "")

turkey17_inven$Value<- as.numeric(as.character(turkey17_inven$Value))

turkey17_inven$Value[is.na(turkey17_inven$Value)] <- 0

turkey17_inven <- turkey17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(turkey17_inven$inventory)
```


```{r}
turkey17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/turkey_sales.csv")

turkey17_sales <- turkey17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

turkey17_sales$State.ANSI[1:161] <- paste0("0", turkey17_sales$State.ANSI[1:161])

turkey17_sales <- turkey17_sales %>%
    arrange(turkey17_sales$County.ANSI, decreasing = FALSE)

turkey17_sales$County.ANSI[1:150]<- paste0("00", turkey17_sales$County.ANSI[1:150])

turkey17_sales$County.ANSI[151:1113]<- paste0("0", turkey17_sales$County.ANSI[151:1113])

turkey17_sales$GEOID <- paste(turkey17_sales$State.ANSI, turkey17_sales$County.ANSI, sep = "")

turkey17_sales$Value<- as.numeric(as.character(turkey17_sales$Value))

turkey17_sales$Value[is.na(turkey17_sales$Value)] <- 0

turkey17_sales <- turkey17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(turkey17_sales$sales)
```

```{r}
turkey <- merge(turkey17_inven, turkey17_sales, by = "GEOID", all = TRUE)
turkey[is.na(turkey)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
turkey <- turkey %>%
  mutate(man_turkey  = inventory*1/(50)* 116.64405/10^9 + ((sales/2*(2-1)/2))*(1/59)*100.411245/10^9 ) %>%
  dplyr::select(GEOID, man_turkey)

sum(turkey$man_turkey)
```


```{r}
duck17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/duck_inven.csv")

duck17_inven <- duck17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

duck17_inven$State.ANSI[1:236] <- paste0("0", duck17_inven$State.ANSI[1:236])

duck17_inven <- duck17_inven %>%
    arrange(duck17_inven$County.ANSI, decreasing = FALSE)

duck17_inven$County.ANSI[1:206]<- paste0("00", duck17_inven$County.ANSI[1:206])

duck17_inven$County.ANSI[207:1610]<- paste0("0", duck17_inven$County.ANSI[207:1610])

duck17_inven$GEOID <- paste(duck17_inven$State.ANSI, duck17_inven$County.ANSI, sep = "")

duck17_inven$Value<- as.numeric(as.character(duck17_inven$Value))

duck17_inven$Value[is.na(duck17_inven$Value)] <- 0

duck17_inven <- duck17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(duck17_inven$inventory)
```



```{r}
duck17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/duck_sales.csv")

duck17_sales <- duck17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

duck17_sales$State.ANSI[1:136] <- paste0("0", duck17_sales$State.ANSI[1:136])

duck17_sales <- duck17_sales %>%
    arrange(duck17_sales$County.ANSI, decreasing = FALSE)

duck17_sales$County.ANSI[1:130]<- paste0("00", duck17_sales$County.ANSI[1:130])

duck17_sales$County.ANSI[131:974]<- paste0("0", duck17_sales$County.ANSI[131:974])

duck17_sales$GEOID <- paste(duck17_sales$State.ANSI, duck17_sales$County.ANSI, sep = "")

duck17_sales$Value<- as.numeric(as.character(duck17_sales$Value))

duck17_sales$Value[is.na(duck17_sales$Value)] <- 0

duck17_sales <- duck17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(duck17_sales$sales)
```


```{r}
duck <- merge(duck17_inven, duck17_sales, by = "GEOID", all = TRUE)
duck[is.na(duck)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
duck <- duck %>%
  mutate(man_duck  =   (((inventory*1/6)+(sales/6*(6-1)/6))*(1/286)*162.288/10^9)) %>%
  dplyr::select(GEOID, man_duck)

sum(duck$man_duck)
```

## merge all CAFO manure 
```{r}
cattle <- merge(beef, milk17, by = "GEOID", all = TRUE)

cattlehog<- merge(cattle, hog, by = "GEOID", all = TRUE)

chicken <- merge(broiler, layer, by = "GEOID", all = TRUE)

chicken_pullet <- merge(chicken, pullet, by = "GEOID", all = TRUE)

turkey_duck <- merge(turkey, duck, by = "GEOID", all = TRUE)


cattlehog_chicken_pullet <- merge(cattlehog, chicken_pullet, by = "GEOID", all = TRUE)

all <- merge(cattlehog_chicken_pullet, turkey_duck, by = "GEOID", all = TRUE)

all[is.na(all)] <- 0

all <- all %>%
  mutate(total = man_beef + man_milk+ man_hog + man_broiler + man_layer + man_pullet + man_turkey + man_duck) %>%
  mutate(potential_recover = man_beef*0.7871*0.4 + man_milk*0.6844*0.4 + manhog_inven*0.8643*0.25 + manhog_sales*0.9550*0.25 + man_broiler*0.9800*0.6 + man_layer*0.95*0.69 + man_pullet*0.95*0.5 + man_turkey*0.8267*0.5 + 
           man_duck*0.695*0.5) 
```


```{r}
## corn 
corngrainarea <- read.csv("~/Desktop/pig/21 crops/area/corn_grain_area.csv")

corngrainarea <- corngrainarea %>%
  dplyr::select(State.ANSI, County.ANSI, corn_grain_acre)

corngrainarea <- corngrainarea %>%
    arrange(corngrainarea$State.ANSI, decreasing = FALSE)

corngrainarea$State.ANSI[1:195] <- paste0("0", corngrainarea$State.ANSI[1:195])

corngrainarea <- corngrainarea %>%
    arrange(corngrainarea$County.ANSI, decreasing = FALSE)

corngrainarea$County.ANSI[1:192]<- paste0("00", corngrainarea$County.ANSI[1:192])

corngrainarea$County.ANSI[193:1604]<- paste0("0", corngrainarea$County.ANSI[193:1604])

corngrainarea$GEOID <- paste(corngrainarea$State.ANSI, corngrainarea$County.ANSI, sep = "")

corngrainarea$corn_grain_acre <- as.numeric(as.character(corngrainarea$corn_grain_acre))

corngrainarea$corn_grain_acre[is.na(corngrainarea$corn_grain_acre)] <- 0

corngrainarea <- corngrainarea %>%
  dplyr::select(GEOID, corn_grain_acre)

corngrainarea  <- corngrainarea  %>%
  mutate(corn_grain_ha = corn_grain_acre*0.404686) %>%
  mutate(applied_corn = corn_grain_acre*0.163*92*0.45/10^9) %>%
  mutate(applied_corn_re = corn_grain_acre/sum(corn_grain_acre)*0.61755575)
```

```{r}
soybeanarea <- read.csv("~/Desktop/pig/21 crops/area/soybean_area.csv")

soybeanarea <- soybeanarea[1:2200,]

soybeanarea <- soybeanarea %>%
  dplyr::select(State.ANSI, County.ANSI, soybean_acres)

soybeanarea <- soybeanarea   %>%
    arrange(soybeanarea$State.ANSI, decreasing = FALSE)

soybeanarea$State.ANSI[1:134] <- paste0("0", soybeanarea$State.ANSI[1:134])

soybeanarea <- soybeanarea %>%
    arrange(soybeanarea$County.ANSI, decreasing = FALSE)

soybeanarea$County.ANSI[1:153]<- paste0("00", soybeanarea$County.ANSI[1:153])

soybeanarea$County.ANSI[154:1284]<- paste0("0", soybeanarea$County.ANSI[154:1284])

soybeanarea$GEOID <- paste(soybeanarea$State.ANSI, soybeanarea$County.ANSI, sep = "")

soybeanarea$soybean_acres<- as.numeric(as.character(soybeanarea$soybean_acres))

soybeanarea$soybean_acres[is.na(soybeanarea$soybean_acres)] <- 0

soybeanarea <- soybeanarea %>%
  dplyr::select(GEOID, soybean_acres)

soybeanarea <- soybeanarea %>%
  mutate(soybean_ha = soybean_acres*0.404686) %>%
  mutate(applied_soy = soybean_acres*0.023*68*0.45/10^9)%>%
  mutate(applied_soy_re = soybean_acres/sum(soybean_acres)*0.05848457)
```


```{r}
wheatarea <- read.csv("~/Desktop/pig/21 crops/area/wheat_area.csv")

wheatarea <- wheatarea %>%
  dplyr::select(State.ANSI, County.ANSI, wheat_acre)

wheatarea  <- wheatarea   %>%
    arrange(wheatarea$State.ANSI, decreasing = FALSE)

wheatarea$State.ANSI[1:198] <- paste0("0", wheatarea$State.ANSI[1:198])

wheatarea <- wheatarea %>%
    arrange(wheatarea$County.ANSI, decreasing = FALSE)

wheatarea$County.ANSI[1:166]<- paste0("00",wheatarea$County.ANSI[1:166])

wheatarea$County.ANSI[167:1440]<- paste0("0", wheatarea$County.ANSI[167:1440])

wheatarea$GEOID <- paste(wheatarea$State.ANSI,wheatarea$County.ANSI, sep = "")

wheatarea$wheat_acre<- as.numeric(as.character(wheatarea$wheat_acre))

wheatarea$wheat_acre[is.na(wheatarea$wheat_acre)] <- 0

wheatarea <- wheatarea %>%
  dplyr::select(GEOID, wheat_acre)

wheatarea <- wheatarea %>%
  mutate(wheat_ha = wheat_acre*0.404686) %>%
  mutate(applied_wheat = wheat_acre*0.02*78*0.45/10^9)%>%
  mutate(applied_wheat_re = wheat_acre/sum(wheat_acre)*0.03223757)
```


```{r}
cottonarea <- read.csv("~/Desktop/pig/21 crops/area/cotton_area.csv")

cottonarea <- cottonarea %>%
  dplyr::select(State.ANSI, County.ANSI, cotton_acres)

cottonarea  <- cottonarea   %>%
    arrange(cottonarea$State.ANSI, decreasing = FALSE)

cottonarea$State.ANSI[1:99] <- paste0("0", cottonarea$State.ANSI[1:99])

cottonarea <-cottonarea %>%
    arrange(cottonarea$County.ANSI, decreasing = FALSE)

cottonarea$County.ANSI[1:32]<- paste0("00",cottonarea$County.ANSI[1:32])

cottonarea$County.ANSI[33:334]<- paste0("0", cottonarea$County.ANSI[33:334])

cottonarea$GEOID <- paste(cottonarea$State.ANSI,cottonarea$County.ANSI, sep = "")

cottonarea$cotton_acres<- as.numeric(as.character(cottonarea$cotton_acres))

cottonarea$cotton_acres[is.na(cottonarea$cotton_acres)] <- 0

cottonarea <- cottonarea %>%
  dplyr::select(GEOID, cotton_acres)

cottonarea <- cottonarea %>%
  mutate(cotton_ha = cotton_acres*0.404686) %>%
  mutate(applied_cotton = cotton_acres*0.042*83*0.45/10^9)%>%
  mutate(applied_cotton_re = cotton_acres/sum(cotton_acres)*0.01900544)
```

```{r}
barleyarea <- read.csv("~/Desktop/pig/21 crops/area/barley_area.csv")

barleyarea <- barleyarea %>%
  dplyr::select(State.ANSI, County.ANSI, barley_acre)

barleyarea  <- barleyarea   %>%
    arrange(barleyarea $State.ANSI, decreasing = FALSE)

barleyarea$State.ANSI[1:66] <- paste0("0", barleyarea $State.ANSI[1:66])

barleyarea <-barleyarea %>%
    arrange(barleyarea$County.ANSI, decreasing = FALSE)

barleyarea$County.ANSI[1:87]<- paste0("00",barleyarea$County.ANSI[1:87])

barleyarea$County.ANSI[88:720]<- paste0("0", barleyarea$County.ANSI[88:720])

barleyarea$GEOID <- paste(barleyarea$State.ANSI,barleyarea$County.ANSI, sep = "")

barleyarea$barley_acre <- as.numeric(as.character(barleyarea$barley_acre))

barleyarea$barley_acre[is.na(barleyarea$barley_acre)] <- 0

barleyarea <- barleyarea %>%
  dplyr::select(GEOID, barley_acre)

barleyarea <- barleyarea %>%
  mutate(barley_ha = barley_acre*0.404686) %>%
  mutate(applied_barley = barley_acre*0.05*76*0.45/10^9)%>%
  mutate(applied_barley_re = barley_acre/sum(barley_acre)*0.00472758)
```

```{r}
oats <- read.csv("~/Desktop/pig/21 crops/oats.csv")

oats <- oats %>%
  dplyr::select(State.ANSI, County.ANSI, oats_bu)

oats <- oats   %>%
    arrange(oats$State.ANSI, decreasing = FALSE)

oats$State.ANSI[1:94] <- paste0("0", oats$State.ANSI[1:94])

oats <- oats %>%
    arrange(oats$County.ANSI, decreasing = FALSE)

oats$County.ANSI[1:138]<- paste0("00", oats$County.ANSI[1:138])

oats$County.ANSI[139:1213]<- paste0("0", oats$County.ANSI[139:1213])

oats$GEOID <- paste(oats$State.ANSI, oats$County.ANSI, sep = "")

oats$oats_bu<- as.numeric(as.character(oats$oats_bu))

oats$oats_bu[is.na(oats$oats_bu)] <- 0

oats <- oats %>%
  dplyr::select(GEOID, oats_bu)

oats<- oats %>%
  mutate(oats_acre = oats_bu/61.7) %>%
  mutate(applied_oats = oats_acre*0.12*72*0.45/10^9) %>%
  mutate(applied_oats_re = oats_acre/sum(oats_acre)*0.01198453)
```


```{r}
peanutarea <- read.csv("~/Desktop/pig/21 crops/area/peanut_area.csv")

peanutarea <- peanutarea %>%
  dplyr::select(State.ANSI, County.ANSI, peanut_acres)

peanutarea <- peanutarea   %>%
    arrange(peanutarea$State.ANSI, decreasing = FALSE)

peanutarea$State.ANSI[1:65] <- paste0("0", peanutarea$State.ANSI[1:65])

peanutarea <- peanutarea %>%
    arrange(peanutarea$County.ANSI, decreasing = FALSE)

peanutarea$County.ANSI[1:25]<- paste0("00", peanutarea$County.ANSI[1:25])

peanutarea$County.ANSI[26:253]<- paste0("0", peanutarea$County.ANSI[26:253])

peanutarea$GEOID <- paste(peanutarea$State.ANSI, peanutarea$County.ANSI, sep = "")

peanutarea$peanut_acres<- as.numeric(as.character(peanutarea$peanut_acres))

peanutarea$peanut_acres[is.na(peanutarea$peanut_acres)] <- 0

peanutarea <- peanutarea %>%
  dplyr::select(GEOID, peanut_acres)

peanutarea<- peanutarea %>%
  mutate(peanut_ha = peanut_acres*0.404686) %>%
  mutate(applied_peanut = peanut_acres*0.122*68*0.45/10^9) %>%
  mutate(applied_peanut_re = peanut_acres/sum(peanut_acres)*0.00617834)
```

```{r}
hayarea <- read.csv("~/Desktop/pig/21 crops/area/hay_area.csv")

hayarea <- hayarea %>%
  dplyr::select(State.ANSI, County.ANSI, hay_acres)

hayarea <- hayarea %>%
    arrange(hayarea$State.ANSI, decreasing = FALSE)

hayarea$State.ANSI[1:286] <- paste0("0", hayarea$State.ANSI[1:286])

hayarea <- hayarea %>%
    arrange(hayarea$County.ANSI, decreasing = FALSE)

hayarea$County.ANSI[1:237]<- paste0("00", hayarea$County.ANSI[1:237])

hayarea$County.ANSI[238:1873]<- paste0("0", hayarea$County.ANSI[238:1873])

hayarea$GEOID <- paste(hayarea$State.ANSI, hayarea$County.ANSI, sep = "")

hayarea$hay_acres <- as.numeric(as.character(hayarea$hay_acres ))

hayarea$hay_acres [is.na(hayarea$hay_acres )] <- 0

hayarea <- hayarea %>%
  dplyr::select(GEOID, hay_acres)

hayarea <- hayarea  %>%
  mutate(hay_ha = hay_acres*0.404686) %>%
  mutate(applied_hay_re = hay_acres/sum(hay_acres)*0.079595596) ## adjutsed applied manure on hay due to constrain for harvested hay 
```


```{r}
cornsoy <- merge(corngrainarea, soybeanarea, by = "GEOID", all = TRUE)

cornsoywheat <- merge(cornsoy, wheatarea, by = "GEOID", all = TRUE)

cornsoywheatct <- merge(cornsoywheat, cottonarea, by = "GEOID", all = TRUE)

cornsoywheatctbl <- merge(cornsoywheatct, barleyarea, by = "GEOID", all = TRUE)

cornsoywheatctbloat <- merge(cornsoywheatctbl, oats, by = "GEOID", all = TRUE)

allcrop <- merge(cornsoywheatctbloat, peanutarea, by = "GEOID", all = TRUE)

allcrop <- merge(allcrop, hayarea, by = "GEOID", all = TRUE)

allcrop[is.na(allcrop)] <- 0


allcrop <- allcrop %>%
  dplyr::select(GEOID, applied_corn_re, applied_soy_re, applied_wheat_re, applied_cotton_re, applied_barley_re, applied_oats_re, applied_peanut_re, applied_hay_re) %>%
  mutate(applied_manure_re = applied_corn_re + applied_soy_re + applied_wheat_re + applied_cotton_re + applied_barley_re + applied_oats_re + applied_peanut_re + applied_hay_re)

allcrop <- allcrop[!duplicated(allcrop[ ,"GEOID", ]),]  # Delete rows

```


```{r}
counties <- st_read("~/Desktop/NUGIS data/data/cb_2018_us_county_500k/cb_2018_us_county_500k.shp")

counties <- counties %>%
  filter(STATEFP %in% c("01", "05", "04", "06", "08", "09", "10", "12", "13", "19", "16", "17",
                        "18", "20", "21", "22", "25", "24", "23", "26", "27", "29", "28",
                        "30", "37", "38", "31", "33", "34", "35", "32", "36", "39", "40",
                        "41", "42", "44", "45", "46", "47", "48", "49", "51", "50", "53", "55",
                        "54", "56")) 

## plot(st_geometry(counties))

counties<- st_transform(counties, CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"))
```
```{r}
allcrop_map <- merge(counties, allcrop, by = "GEOID", all.x = TRUE)

alllive_map <- merge(counties, all, by = "GEOID", all.x = TRUE)

alllive_map <- alllive_map %>%
  rename(total_cafo = total)

allcrop_map_redu <- allcrop_map %>%
  dplyr::select(GEOID, applied_manure_re)

allcrop_map_redu <- st_drop_geometry(allcrop_map_redu)

crop_manure <- merge(allcrop_map_redu, alllive_map, by = "GEOID", all = TRUE)

crop_manure[is.na(crop_manure)] <- 0

```


## quantify M1, M2 

```{r}
crop_manure <- crop_manure %>%
  mutate(M1 = potential_recover - applied_manure_re) %>%
  mutate(M2 = total_cafo - potential_recover)

##-----------------------------------------make values of M1 <0 to 0 

##crop_manure$M1[crop_manure$M1 < 0] <- 0 

```


## quantify C1, C2 

## 21 US common crop production

```{r}
hay17 <- read.csv("~/Desktop/pig/21 crops/hay2017.csv")

hay17 <- hay17 %>%
  dplyr::select(State.ANSI, County.ANSI, hay_tons)

hay17 <- hay17 %>%
    arrange(hay17$State.ANSI, decreasing = FALSE)

hay17$State.ANSI[1:286] <- paste0("0", hay17$State.ANSI[1:286])

hay17 <- hay17 %>%
    arrange(hay17$County.ANSI, decreasing = FALSE)

hay17$County.ANSI[1:237]<- paste0("00", hay17$County.ANSI[1:237])

hay17$County.ANSI[238:1873]<- paste0("0", hay17$County.ANSI[238:1873])

hay17$GEOID <- paste(hay17$State.ANSI, hay17$County.ANSI, sep = "")

hay17$hay_tons<- as.numeric(as.character(hay17$hay_tons))

hay17$hay_tons[is.na(hay17$hay_tons)] <- 0

hay17 <- hay17 %>%
  dplyr::select(GEOID, hay_tons)
```

```{r}
alfalfa17 <- read.csv("~/Desktop/pig/21 crops/alfalfa.csv")

alfalfa17 <- alfalfa17[1:2688, ]

alfalfa17 <- alfalfa17 %>%
  dplyr::select(State.ANSI, County.ANSI, alfalfa_tons)

alfalfa17 <- alfalfa17 %>%
    arrange(alfalfa17$State.ANSI, decreasing = FALSE)

alfalfa17$State.ANSI[1:210] <- paste0("0", alfalfa17$State.ANSI[1:210])

alfalfa17 <- alfalfa17 %>%
    arrange(alfalfa17$County.ANSI, decreasing = FALSE)

alfalfa17$County.ANSI[1:215]<- paste0("00", alfalfa17$County.ANSI[1:215])

alfalfa17$County.ANSI[216:1672]<- paste0("0", alfalfa17$County.ANSI[216:1672])

alfalfa17$GEOID <- paste(alfalfa17$State.ANSI, alfalfa17$County.ANSI, sep = "")

alfalfa17$alfalfa_tons<- as.numeric(as.character(alfalfa17$alfalfa_tons))

alfalfa17$alfalfa_tons[is.na(alfalfa17$alfalfa_tons)] <- 0

alfalfa17 <- alfalfa17 %>%
  dplyr::select(GEOID, alfalfa_tons)

```

```{r}
hayalfa <- merge(counties, hay17, by = "GEOID", all.x = TRUE)

hayalfab <- st_drop_geometry(hayalfa)

hayalfac <- merge(hayalfab, alfalfa17, by = "GEOID", all.x = TRUE)

hayalfac$hay_tons[is.na(hayalfac$hay_tons)] <- 0
hayalfac$alfalfa_tons[is.na(hayalfac$alfalfa_tons)] <- 0

hayalfac <- hayalfac %>%
  mutate(otherhay_tons = hay_tons - alfalfa_tons) %>%
  mutate(alfal_TgN = alfalfa_tons* 0.0056/10^6) %>%
  mutate(otherhay_TgN = otherhay_tons*0.0025/10^6) %>%
  mutate(alfal_TgN1 = alfalfa_tons* 0.0255/10^6) %>%
  mutate(otherhay_TgN1 = otherhay_tons*0.0145/10^6)

##hayalfa <- merge(counties, hayalfa, by = "GEOID", all.x = TRUE)
```

```{r}
barley2017 <- read.csv("~/Desktop/pig/21 crops/barley.csv")

barley2017 <- barley2017[1:992, ]

barley2017 <- barley2017 %>%
  dplyr::select(State.ANSI, County.ANSI, barley_bushels)

barley2017 <- barley2017 %>%
    arrange(barley2017$State.ANSI, decreasing = FALSE)

barley2017$State.ANSI[1:66] <- paste0("0", barley2017$State.ANSI[1:66])

barley2017 <- barley2017 %>%
    arrange(barley2017$County.ANSI, decreasing = FALSE)

barley2017$County.ANSI[1:87]<- paste0("00", barley2017$County.ANSI[1:87])

barley2017$County.ANSI[88:720]<- paste0("0", barley2017$County.ANSI[88:720])

barley2017$GEOID <- paste(barley2017$State.ANSI, barley2017$County.ANSI, sep = "")

barley2017$barley_bushels <- as.numeric(as.character(barley2017$barley_bushels))

barley2017$barley_bushels[is.na(barley2017$barley_bushels)] <- 0

barley2017 <- barley2017 %>%
  dplyr::select(GEOID, barley_bushels)


barley2017 <- barley2017 %>%
  mutate(barley_TgN = barley_bushels* 0.0176* 21.772/10^9) %>%
  mutate(barley_TgN1 = barley_bushels* 0.0206* 21.772/10^9)
```

```{r}
corngrain17 <- read.csv("~/Desktop/pig/21 crops/corn_grain.csv")

corngrain17 <- corngrain17 %>%
  dplyr::select(State.ANSI, County.ANSI, corngrain_bu)

corngrain17 <- corngrain17 %>%
    arrange(corngrain17$State.ANSI, decreasing = FALSE)

corngrain17$State.ANSI[1:195] <- paste0("0", corngrain17$State.ANSI[1:195])

corngrain17 <- corngrain17 %>%
    arrange(corngrain17$County.ANSI, decreasing = FALSE)

corngrain17$County.ANSI[1:192]<- paste0("00", corngrain17$County.ANSI[1:192])

corngrain17$County.ANSI[193:1604]<- paste0("0", corngrain17$County.ANSI[193:1604])

corngrain17$GEOID <- paste(corngrain17$State.ANSI, corngrain17$County.ANSI, sep = "")

corngrain17$corngrain_bu <- as.numeric(as.character(corngrain17$corngrain_bu))

corngrain17$corngrain_bu[is.na(corngrain17$corngrain_bu)] <- 0

corngrain17 <- corngrain17 %>%
  dplyr::select(GEOID, corngrain_bu)


corngrain17 <- corngrain17 %>%
  mutate(corngrain_TgN = corngrain_bu* 0.0152* 25.4/10^9) %>%
  mutate(corngrain_TgN1 = corngrain_bu* 0.012* 25.4/10^9)
```

```{r}
cornsilage17 <- read.csv("~/Desktop/pig/21 crops/corn_silage.csv")

cornsilage17 <- cornsilage17 %>%
  dplyr::select(State.ANSI, County.ANSI, corn_silage_tons)

cornsilage17 <- cornsilage17 %>%
    arrange(cornsilage17$State.ANSI, decreasing = FALSE)

cornsilage17$State.ANSI[1:128] <- paste0("0", cornsilage17$State.ANSI[1:128])

cornsilage17 <- cornsilage17 %>%
    arrange(cornsilage17$County.ANSI, decreasing = FALSE)

cornsilage17$County.ANSI[1:181]<- paste0("00", cornsilage17$County.ANSI[1:181])

cornsilage17$County.ANSI[182:1339]<- paste0("0", cornsilage17$County.ANSI[182:1339])

cornsilage17$GEOID <- paste(cornsilage17 $State.ANSI, cornsilage17$County.ANSI, sep = "")

cornsilage17$corn_silage_tons <- as.numeric(as.character(cornsilage17$corn_silage_tons))

cornsilage17$corn_silage_tons[is.na(cornsilage17$corn_silage_tons)] <- 0

cornsilage17 <- cornsilage17 %>%
  dplyr::select(GEOID, corn_silage_tons)

cornsilage17 <- cornsilage17 %>%
  mutate(corn_silage_TgN = corn_silage_tons* 0.002/10^6) %>%
  mutate(corn_silage_TgN1 = corn_silage_tons* 0.0049/10^6)
```

```{r}
cotton17 <- read.csv("~/Desktop/pig/21 crops/cotton.csv")

cotton17 <- cotton17 %>%
  dplyr::select(State.ANSI, County.ANSI, cotton_bales)

cotton17 <- cotton17 %>%
    arrange(cotton17$State.ANSI, decreasing = FALSE)

cotton17$State.ANSI[1:99] <- paste0("0", cotton17$State.ANSI[1:99])

cotton17 <- cotton17 %>%
    arrange(cotton17$County.ANSI, decreasing = FALSE)

cotton17$County.ANSI[1:32]<- paste0("00", cotton17$County.ANSI[1:32])

cotton17$County.ANSI[33:334]<- paste0("0", cotton17$County.ANSI[33:334])

cotton17$GEOID <- paste(cotton17$State.ANSI, cotton17$County.ANSI, sep = "")

cotton17$cotton_bales <- as.numeric(as.character(cotton17$cotton_bales))

cotton17$cotton_bales[is.na(cotton17$cotton_bales)] <- 0

cotton17 <- cotton17 %>%
  dplyr::select(GEOID, cotton_bales)

cotton17<- cotton17 %>%
  mutate(cotton_TgN = cotton_bales* 0.00088*0.21772/10^6) %>%
  mutate(cotton_TgN1 = cotton_bales* 0.066*0.21772/10^6)

```

```{r}
peanut17 <- read.csv("~/Desktop/pig/21 crops/peanut.csv")

peanut17 <- peanut17 %>%
  dplyr::select(State.ANSI, County.ANSI, peanut_lbs)

peanut17 <- peanut17 %>%
    arrange(peanut17$State.ANSI, decreasing = FALSE)

peanut17$State.ANSI[1:49] <- paste0("0", peanut17$State.ANSI[1:49])

peanut17 <- peanut17 %>%
    arrange(peanut17$County.ANSI, decreasing = FALSE)

peanut17$County.ANSI[1:17]<- paste0("00", peanut17$County.ANSI[1:17])

peanut17$County.ANSI[18:192]<- paste0("0", peanut17$County.ANSI[18:192])

peanut17$GEOID <- paste(peanut17$State.ANSI, peanut17$County.ANSI, sep = "")

peanut17$peanut_lbs <- as.numeric(as.character(peanut17$peanut_lbs))

peanut17$peanut_lbs[is.na(peanut17$peanut_lbs)] <- 0

peanut17 <- peanut17 %>%
  dplyr::select(GEOID, peanut_lbs)

peanut17<- peanut17 %>%
  mutate(peanut_TgN = peanut_lbs* 0.03888*0.453592/10^9) %>%
  mutate(peanut_TgN1 = peanut_lbs* 0.035*0.453592/10^9)
```

```{r}

rice17 <- read.csv("~/Desktop/pig/21 crops/rice.csv")

rice17 <- rice17 %>%
  dplyr::select(State.ANSI, County.ANSI, rice_CWT)

rice17 <- rice17 %>%
    arrange(rice17$State.ANSI, decreasing = FALSE)

rice17$State.ANSI[1:52] <- paste0("0", rice17$State.ANSI[1:52])

rice17 <- rice17 %>%
    arrange(rice17$County.ANSI, decreasing = FALSE)

rice17$County.ANSI[1:7]<- paste0("00", rice17$County.ANSI[1:7])

rice17$County.ANSI[8:83]<- paste0("0", rice17$County.ANSI[8:83])

rice17$GEOID <- paste(rice17$State.ANSI,rice17$County.ANSI, sep = "")

rice17$rice_CWT <- as.numeric(as.character(rice17$rice_CWT))

rice17$rice_CWT[is.na(rice17$rice_CWT)] <- 0

rice17 <- rice17 %>%
  dplyr::select(GEOID, rice_CWT)

rice17<- rice17 %>%
  mutate(rice_TgN = rice_CWT* 0.016*50.8023/10^9) %>%
  mutate(rice_TgN1 = rice_CWT* 0.011*50.8023/10^9)

```

```{r}
sorghum17 <- read.csv("~/Desktop/pig/21 crops/sorghum.csv")

sorghum17 <- sorghum17 %>%
  dplyr::select(State.ANSI, County.ANSI, sorghum_bu)

sorghum17  <- sorghum17  %>%
    arrange(sorghum17 $State.ANSI, decreasing = FALSE)

sorghum17$State.ANSI[1:86] <- paste0("0", sorghum17$State.ANSI[1:86])

sorghum17 <- sorghum17 %>%
    arrange(sorghum17$County.ANSI, decreasing = FALSE)

sorghum17$County.ANSI[1:66]<- paste0("00",sorghum17$County.ANSI[1:66])

sorghum17$County.ANSI[67:580]<- paste0("0", sorghum17$County.ANSI[67:580])

sorghum17$GEOID <- paste(sorghum17$State.ANSI,sorghum17$County.ANSI, sep = "")

sorghum17$sorghum_bu <- as.numeric(as.character(sorghum17$sorghum_bu))

sorghum17$sorghum_bu[is.na(sorghum17$sorghum_bu)] <- 0

sorghum17 <- sorghum17 %>%
  dplyr::select(GEOID, sorghum_bu)

sorghum17 <- sorghum17 %>%
  mutate(sorghum_TgN = sorghum_bu* 0.0161*25.4012/10^9) %>%
  mutate(sorghum_TgN1 = sorghum_bu* 0.0132*25.4012/10^9)
```

```{r}
tobacco17 <- read.csv("~/Desktop/pig/21 crops/tobacco.csv")

tobacco17 <- tobacco17 %>%
  dplyr::select(State.ANSI, County.ANSI, tobacco_lb)

tobacco17  <- tobacco17  %>%
    arrange(tobacco17$State.ANSI, decreasing = FALSE)

tobacco17$State.ANSI[1:2] <- paste0("0", tobacco17$State.ANSI[1:2])

tobacco17 <- tobacco17 %>%
    arrange(tobacco17$County.ANSI, decreasing = FALSE)

tobacco17$County.ANSI[1:17]<- paste0("00",tobacco17$County.ANSI[1:17])

tobacco17$County.ANSI[18:172]<- paste0("0", tobacco17$County.ANSI[18:172])

tobacco17$GEOID <- paste(tobacco17$State.ANSI,tobacco17$County.ANSI, sep = "")

tobacco17$tobacco_lb <- as.numeric(as.character(tobacco17$tobacco_lb))

tobacco17$tobacco_lb[is.na(tobacco17$tobacco_lb)] <- 0

tobacco17 <- tobacco17 %>%
  dplyr::select(GEOID, tobacco_lb)

tobacco17 <- tobacco17 %>%
  mutate(tobacco_TgN = tobacco_lb* 0.04*0.453592/10^9) %>%
  mutate(tobacco_TgN1 = tobacco_lb* 0.036*0.453592/10^9)
```

```{r}
wheat17 <- read.csv("~/Desktop/pig/21 crops/wheat.csv")

wheat17 <- wheat17 %>%
  dplyr::select(State.ANSI, County.ANSI, wheat_bu)

wheat17 <- wheat17  %>%
    arrange(wheat17$State.ANSI, decreasing = FALSE)

wheat17$State.ANSI[1:198] <- paste0("0", wheat17$State.ANSI[1:198])

wheat17 <- wheat17 %>%
    arrange(wheat17$County.ANSI, decreasing = FALSE)

wheat17$County.ANSI[1:166]<- paste0("00",wheat17$County.ANSI[1:166])

wheat17$County.ANSI[167:1440]<- paste0("0", wheat17$County.ANSI[167:1440])

wheat17$GEOID <- paste(wheat17$State.ANSI,wheat17$County.ANSI, sep = "")

wheat17$wheat_bu <- as.numeric(as.character(wheat17$wheat_bu))

wheat17$wheat_bu[is.na(wheat17$wheat_bu)] <- 0

wheat17 <- wheat17 %>%
  dplyr::select(GEOID, wheat_bu, State.ANSI)

wheat17s <- wheat17 %>%
  filter(State.ANSI %in% c("27", "30", "38", "56")) 

wheat17s <- wheat17s %>%
  mutate(wheat_TgN1 = wheat_bu* 0.0248*27.216/10^9)

wheat17o <- wheat17 %>%
  filter(!State.ANSI %in% c("27", "30", "38", "56")) 

wheat17o <- wheat17o %>%
  mutate(wheat_TgN1 = wheat_bu* 0.0193*27.216/10^9)

wheat17t <- rbind(wheat17o, wheat17s)


wheat17 <- wheat17t %>%
  mutate(wheat_TgN = wheat_bu* 0.01952*27.216/10^9) 

```

```{r}
sunflower17 <- read.csv("~/Desktop/pig/21 crops/sunflower.csv")

sunflower17 <- sunflower17 %>%
  dplyr::select(State.ANSI, County.ANSI, sunflower_lbs)

sunflower17 <- sunflower17  %>%
    arrange(sunflower17$State.ANSI, decreasing = FALSE)

sunflower17$State.ANSI[1:47] <- paste0("0", sunflower17$State.ANSI[1:47])

sunflower17 <-sunflower17 %>%
    arrange(sunflower17$County.ANSI, decreasing = FALSE)

sunflower17$County.ANSI[1:46]<- paste0("00",sunflower17$County.ANSI[1:46])

sunflower17$County.ANSI[47:357]<- paste0("0", sunflower17$County.ANSI[47:357])

sunflower17$GEOID <- paste(sunflower17$State.ANSI,sunflower17$County.ANSI, sep = "")

sunflower17$sunflower_lbs <- as.numeric(as.character(sunflower17$sunflower_lbs))

sunflower17$sunflower_lbs[is.na(sunflower17$sunflower_lbs)] <- 0

sunflower17 <- sunflower17 %>%
  dplyr::select(GEOID, sunflower_lbs)

sunflower17 <- sunflower17 %>%
  mutate(sunflower_TgN = sunflower_lbs* 0.01968*0.453592/10^9) %>%
  mutate(sunflower_TgN1 = sunflower_lbs* 0.027*0.453592/10^9)
```

```{r}
sugarcane17 <- read.csv("~/Desktop/pig/21 crops/sugarcane2.csv")

sugarcane17 <- sugarcane17 %>%
  dplyr::select(State.ANSI, County.ANSI, sugarcane_tons)

sugarcane17 <- sugarcane17  %>%
    arrange(sugarcane17$State.ANSI, decreasing = FALSE)

sugarcane17 <-sugarcane17 %>%
    arrange(sugarcane17$County.ANSI, decreasing = FALSE)

sugarcane17$County.ANSI[1:8]<- paste0("00",sugarcane17$County.ANSI[1:8])

sugarcane17$County.ANSI[9:33]<- paste0("0", sugarcane17$County.ANSI[9:33])

sugarcane17$GEOID <- paste(sugarcane17$State.ANSI,sugarcane17$County.ANSI, sep = "")

sugarcane17$sugarcane_tons <- as.numeric(as.character(sugarcane17$sugarcane_tons))

sugarcane17$sugarcane_tons[is.na(sugarcane17$sugarcane_tons)] <- 0

sugarcane17 <- sugarcane17 %>%
  dplyr::select(GEOID, sugarcane_tons)

sugarcane17 <- sugarcane17 %>%
  mutate(sugarcane_TgN = sugarcane_tons* 0.00032/10^6) %>%
  mutate(sugarcane_TgN1 = sugarcane_tons* 0.001/10^6)
```

```{r}
sugarbeet17 <- read.csv("~/Desktop/pig/21 crops/sugarbeet.csv")

sugarbeet17 <- sugarbeet17 %>%
  dplyr::select(State.ANSI, County.ANSI, sugarbeet_tons)

sugarbeet17 <- sugarbeet17  %>%
    arrange(sugarbeet17$State.ANSI, decreasing = FALSE)

sugarbeet17$State.ANSI[1:13] <- paste0("0", sugarbeet17$State.ANSI[1:13])

sugarbeet17 <-sugarbeet17 %>%
    arrange(sugarbeet17$County.ANSI, decreasing = FALSE)

sugarbeet17$County.ANSI[1:10]<- paste0("00",sugarbeet17$County.ANSI[1:10])

sugarbeet17$County.ANSI[11:89]<- paste0("0", sugarbeet17$County.ANSI[11:89])

sugarbeet17$GEOID <- paste(sugarbeet17$State.ANSI,sugarbeet17$County.ANSI, sep = "")

sugarbeet17$sugarbeet_tons <- as.numeric(as.character(sugarbeet17$sugarbeet_tons))

sugarbeet17$sugarbeet_tons[is.na(sugarbeet17$sugarbeet_tons)] <- 0

sugarbeet17 <- sugarbeet17 %>%
  dplyr::select(GEOID, sugarbeet_tons)

sugarbeet17 <- sugarbeet17 %>%
  mutate(sugarbeet_TgN = sugarbeet_tons* 0.00208/10^6) %>%
  mutate(sugarbeet_TgN1 = sugarbeet_tons* 0.0019/10^6)
```

```{r}
soybean17 <- read.csv("~/Desktop/pig/21 crops/soybeans.csv")

soybean17 <- soybean17[1:2200, ]

soybean17 <- soybean17 %>%
  dplyr::select(State.ANSI, County.ANSI, soybean_bushels)

soybean17<- soybean17  %>%
    arrange(soybean17$State.ANSI, decreasing = FALSE)

soybean17$State.ANSI[1:134] <- paste0("0", soybean17$State.ANSI[1:134])

soybean17 <-soybean17 %>%
    arrange(soybean17$County.ANSI, decreasing = FALSE)

soybean17$County.ANSI[1:153]<- paste0("00",soybean17$County.ANSI[1:153])

soybean17$County.ANSI[154:1284]<- paste0("0", soybean17$County.ANSI[154:1284])

soybean17$GEOID <- paste(soybean17$State.ANSI,soybean17$County.ANSI, sep = "")

soybean17$soybean_bushels <- as.numeric(as.character(soybean17$soybean_bushels))

soybean17$soybean_bushels[is.na(soybean17$soybean_bushels)] <- 0

soybean17 <- soybean17 %>%
  dplyr::select(GEOID, soybean_bushels)

soybean17 <- soybean17 %>%
  mutate(soybean_TgN = soybean_bushels* 27.2155*0.06088/10^9) %>%
  mutate(soybean_TgN1 = soybean_bushels* 27.2155*0.0542/10^9)

```

```{r}
canola17 <- read.csv("~/Desktop/pig/21 crops/canola.csv")

canola17 <- canola17 %>%
  dplyr::select(State.ANSI, County.ANSI, canola_lbs)

canola17<- canola17  %>%
    arrange(canola17$State.ANSI, decreasing = FALSE)

canola17$State.ANSI[1:10] <- paste0("0", canola17$State.ANSI[1:10])

canola17 <-canola17 %>%
    arrange(canola17$County.ANSI, decreasing = FALSE)

canola17$County.ANSI[1:21]<- paste0("00",canola17$County.ANSI[1:21])

canola17$County.ANSI[22:193]<- paste0("0", canola17$County.ANSI[22:193])

canola17$GEOID <- paste(canola17$State.ANSI,canola17$County.ANSI, sep = "")

canola17$canola_lbs <- as.numeric(as.character(canola17$canola_lbs))

canola17$canola_lbs[is.na(canola17$canola_lbs)] <- 0

canola17 <- canola17 %>%
  dplyr::select(GEOID, canola_lbs)

canola17 <- canola17 %>%
  mutate(canola_TgN = canola_lbs* 0.453592*0.03136/10^9) %>%
  mutate(canola_TgN1 = canola_lbs* 0.453592*0.038/10^9)

```

```{r}
drybeans17 <- read.csv("~/Desktop/pig/21 crops/drybeans_2017.csv")

drybeans17 <- drybeans17 %>%
  dplyr::select(State.ANSI, County.ANSI, beans_dry_cwt)

drybeans17 <- drybeans17  %>%
    arrange(drybeans17$State.ANSI, decreasing = FALSE)

drybeans17$State.ANSI[1:66] <- paste0("0", drybeans17$State.ANSI[1:66])

drybeans17 <- drybeans17 %>%
    arrange(drybeans17$County.ANSI, decreasing = FALSE)

drybeans17$County.ANSI[1:42]<- paste0("00",drybeans17$County.ANSI[1:42])

drybeans17$County.ANSI[43:320]<- paste0("0", drybeans17$County.ANSI[43:320])

drybeans17$GEOID <- paste(drybeans17$State.ANSI,drybeans17$County.ANSI, sep = "")

drybeans17$beans_dry_cwt <- as.numeric(as.character(drybeans17$beans_dry_cwt))

drybeans17$beans_dry_cwt[is.na(drybeans17$beans_dry_cwt)] <- 0

drybeans17 <- drybeans17 %>%
  dplyr::select(GEOID, beans_dry_cwt)

drybeans17 <- drybeans17 %>%
  mutate(drybeans_TgN = beans_dry_cwt/19.684/10^6* 0.0446) %>%
  mutate(drybeans_TgN1 = beans_dry_cwt/19.684/10^6* 0.0446)
```


```{r}
NUdata <- read.csv("~/Desktop/NUGIS data/NuGIS_County_Data.csv")

NUdata16 <- NUdata %>%
  filter(year == "2016") %>%
  dplyr::select(year, state, county, FIPS,Total_Harvested_Cropland_Acres) ## filter year in 2016

NUdata16$FIPS[1:285] <- paste0("0", NUdata16$FIPS[1:285])

names(NUdata16)[names(NUdata16) == "FIPS"] <- "GEOID"

NUdata16 <- NUdata16 %>%
  mutate(potatoes_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*20.45343*0.00256) %>%
  mutate(potatoes_TgN1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*20.45343*0.0029)

NUdata16 <- NUdata16 %>%
  mutate(apples_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*5.24067*0.0005) %>%
  mutate(apples_TgN1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*5.24067*0.003)

NUdata16 <- NUdata16 %>%
  mutate(oranges_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*4.61576*0.0018) %>%
  mutate(oranges_TgN1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*4.61576*0.0044)

NUdata16 <- NUdata16 %>%
  mutate(sweetcorn_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*3.846000031*0.00288) %>%
  mutate(sweetcorn_TgN1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*3.846000031*0.0139)



```


```{r}
hb <- merge(hayalfac, barley2017, by = "GEOID", all = TRUE)

grainsilage <- merge(corngrain17, cornsilage17, by = "GEOID", all = TRUE)

hbcorn <- merge(hb, grainsilage, by = "GEOID", all = TRUE)

cp <- merge(cotton17, peanut17, by = "GEOID", all = TRUE)

rs <- merge(rice17, sorghum17, by = "GEOID", all = TRUE)

cprs <- merge(cp, rs, by = "GEOID", all = TRUE)

hbcorncprs <- merge(hbcorn,cprs, by = "GEOID", all = TRUE )

tw <- merge(tobacco17, wheat17, by = "GEOID", all = TRUE)

ss <- merge(sunflower17, sugarcane17, by = "GEOID", all = TRUE)

ss2 <- merge(sugarbeet17, soybean17, by = "GEOID", all = TRUE)

twss <- merge(tw,ss, by = "GEOID", all = TRUE )

twss2 <- merge(twss, ss2, by = "GEOID", all = TRUE)

hbcotncprstwss2 <- merge(hbcorncprs, twss2, by =  "GEOID", all = TRUE)

hbcotncprstwss2 <- merge(hbcotncprstwss2, canola17, by = "GEOID", all = TRUE)

hbcotncprstwss3 <- merge(hbcotncprstwss2, drybeans17, by = "GEOID", all = TRUE)

hbcotncprstwss3 <- merge(counties, hbcotncprstwss3, by = "GEOID", all.x = TRUE )

hbcotncprstwss3_new <- hbcotncprstwss3[!duplicated(hbcotncprstwss3[ ,"GEOID", ]),]  # Delete rows



hbcotncprstwss3_new[is.na(hbcotncprstwss3_new)] <- 0

hbcotncprstwss3_newdp <- st_drop_geometry(hbcotncprstwss3_new)

crop17 <- merge(NUdata16,hbcotncprstwss3_newdp, by = "GEOID", all.x = TRUE )

crop17 <- crop17 %>%
  mutate(crop21pro = alfal_TgN1 + otherhay_TgN1 + barley_TgN1 + corngrain_TgN1 + corn_silage_TgN1 + cotton_TgN1 + peanut_TgN1 + rice_TgN1 + sorghum_TgN1 +tobacco_TgN1 +wheat_TgN1 +  sunflower_TgN1 + sugarcane_TgN1 +  sugarbeet_TgN1 +soybean_TgN1 +  drybeans_TgN1 + apples_TgN1 + oranges_TgN1 + potatoes_TgN1 + sweetcorn_TgN1 + canola_TgN1)

crop17 <- crop17 %>%
  mutate(crop21_current = (alfal_TgN1/0.8 + otherhay_TgN1/0.8 + barley_TgN1/0.61 + corngrain_TgN1/0.71 + corn_silage_TgN1/0.71 + cotton_TgN1/0.77 + peanut_TgN1/0.41 +rice_TgN1/0.44 + sorghum_TgN1/0.61 + tobacco_TgN1*1.18 + wheat_TgN1/0.5 + sunflower_TgN1/0.41 + sugarcane_TgN1/0.5 + sugarbeet_TgN1/0.5 + soybean_TgN1/0.83 + canola_TgN1/0.41 + oranges_TgN1/0.25 + apples_TgN1/0.25 +drybeans_TgN1/0.5 + potatoes_TgN1/0.5 + sweetcorn_TgN1/0.25)) %>%
  mutate(crop21_NUE80 = (crop21pro-soybean_TgN1 )/0.8 + soybean_TgN1/0.83) %>%
  mutate(crop21nighty = crop21pro/0.9)

```



```{r}
barleyarea <- read.csv("~/Desktop/pig/21 crops/area/barley_area.csv")

barleyarea <- barleyarea %>%
  dplyr::select(State.ANSI, County.ANSI, barley_acre)

barleyarea  <- barleyarea   %>%
    arrange(barleyarea $State.ANSI, decreasing = FALSE)

barleyarea$State.ANSI[1:66] <- paste0("0", barleyarea $State.ANSI[1:66])

barleyarea <-barleyarea %>%
    arrange(barleyarea$County.ANSI, decreasing = FALSE)

barleyarea$County.ANSI[1:87]<- paste0("00",barleyarea$County.ANSI[1:87])

barleyarea$County.ANSI[88:720]<- paste0("0", barleyarea$County.ANSI[88:720])

barleyarea$GEOID <- paste(barleyarea$State.ANSI,barleyarea$County.ANSI, sep = "")

barleyarea$barley_acre <- as.numeric(as.character(barleyarea$barley_acre))

barleyarea$barley_acre[is.na(barleyarea$barley_acre)] <- 0

barleyarea <- barleyarea %>%
  dplyr::select(GEOID, barley_acre)

barleyarea <- barleyarea %>%
  mutate(barley_ha = barley_acre*0.404686)
```

```{r}
cottonarea <- read.csv("~/Desktop/pig/21 crops/area/cotton_area.csv")

cottonarea <- cottonarea %>%
  dplyr::select(State.ANSI, County.ANSI, cotton_acres)

cottonarea  <- cottonarea   %>%
    arrange(cottonarea$State.ANSI, decreasing = FALSE)

cottonarea$State.ANSI[1:99] <- paste0("0", cottonarea$State.ANSI[1:99])

cottonarea <-cottonarea %>%
    arrange(cottonarea$County.ANSI, decreasing = FALSE)

cottonarea$County.ANSI[1:32]<- paste0("00",cottonarea$County.ANSI[1:32])

cottonarea$County.ANSI[33:334]<- paste0("0", cottonarea$County.ANSI[33:334])

cottonarea$GEOID <- paste(cottonarea$State.ANSI,cottonarea$County.ANSI, sep = "")

cottonarea$cotton_acres<- as.numeric(as.character(cottonarea$cotton_acres))

cottonarea$cotton_acres[is.na(cottonarea$cotton_acres)] <- 0

cottonarea <- cottonarea %>%
  dplyr::select(GEOID, cotton_acres)

cottonarea <- cottonarea %>%
  mutate(cotton_ha = cotton_acres*0.404686)
```

```{r}
wheatarea <- read.csv("~/Desktop/pig/21 crops/area/wheat_area.csv")

wheatarea <- wheatarea %>%
  dplyr::select(State.ANSI, County.ANSI, wheat_acre)

wheatarea  <- wheatarea   %>%
    arrange(wheatarea$State.ANSI, decreasing = FALSE)

wheatarea$State.ANSI[1:198] <- paste0("0", wheatarea$State.ANSI[1:198])

wheatarea <- wheatarea %>%
    arrange(wheatarea$County.ANSI, decreasing = FALSE)

wheatarea$County.ANSI[1:166]<- paste0("00",wheatarea$County.ANSI[1:166])

wheatarea$County.ANSI[167:1440]<- paste0("0", wheatarea$County.ANSI[167:1440])

wheatarea$GEOID <- paste(wheatarea$State.ANSI,wheatarea$County.ANSI, sep = "")

wheatarea$wheat_acre<- as.numeric(as.character(wheatarea$wheat_acre))

wheatarea$wheat_acre[is.na(wheatarea$wheat_acre)] <- 0

wheatarea <- wheatarea %>%
  dplyr::select(GEOID, wheat_acre)

wheatarea <- wheatarea %>%
  mutate(wheat_ha = wheat_acre*0.404686)
```

```{r}
ricearea <- read.csv("~/Desktop/pig/21 crops/area/rice_area.csv")

ricearea <- ricearea %>%
  dplyr::select(State.ANSI, County.ANSI, rice_acre)

ricearea  <- ricearea   %>%
    arrange(ricearea$State.ANSI, decreasing = FALSE)

ricearea$State.ANSI[1:89] <- paste0("0", ricearea$State.ANSI[1:89])

ricearea <- ricearea %>%
    arrange(ricearea$County.ANSI, decreasing = FALSE)

ricearea$County.ANSI[1:12]<- paste0("00", ricearea$County.ANSI[1:12])

ricearea$County.ANSI[13:121]<- paste0("0", ricearea$County.ANSI[13:121])

ricearea$GEOID <- paste(ricearea$State.ANSI, ricearea$County.ANSI, sep = "")

ricearea$rice_acre<- as.numeric(as.character(ricearea$rice_acre))

ricearea$rice_acre[is.na(ricearea$rice_acre)] <- 0

ricearea <- ricearea %>%
  dplyr::select(GEOID, rice_acre)

ricearea <- ricearea %>%
  mutate(rice_ha = rice_acre*0.404686)
```

```{r}
sweetcornarea <- read.csv("~/Desktop/pig/21 crops/area/sweetcorn_area.csv")

sweetcornarea <- sweetcornarea %>%
  dplyr::select(State.ANSI, County.ANSI, sweetcorn_acre)

sweetcornarea <- sweetcornarea   %>%
    arrange(sweetcornarea$State.ANSI, decreasing = FALSE)

sweetcornarea$State.ANSI[1:210] <- paste0("0", sweetcornarea$State.ANSI[1:210])

sweetcornarea <- sweetcornarea %>%
    arrange(sweetcornarea$County.ANSI, decreasing = FALSE)

sweetcornarea$County.ANSI[1:185]<- paste0("00", sweetcornarea$County.ANSI[1:185])

sweetcornarea$County.ANSI[186:1424]<- paste0("0", sweetcornarea$County.ANSI[186:1424])

sweetcornarea$GEOID <- paste(sweetcornarea$State.ANSI, sweetcornarea$County.ANSI, sep = "")

sweetcornarea$sweetcorn_acre<- as.numeric(as.character(sweetcornarea$sweetcorn_acre))

sweetcornarea$sweetcorn_acre[is.na(sweetcornarea$sweetcorn_acre)] <- 0

sweetcornarea <- sweetcornarea %>%
  dplyr::select(GEOID, sweetcorn_acre)

sweetcornarea <- sweetcornarea %>%
  mutate(sweetcorn_ha = sweetcorn_acre*0.404686)
```

```{r}
soybeanarea <- read.csv("~/Desktop/pig/21 crops/area/soybean_area.csv")

soybeanarea <- soybeanarea[1:2200,]

soybeanarea <- soybeanarea %>%
  dplyr::select(State.ANSI, County.ANSI, soybean_acres)

soybeanarea <- soybeanarea   %>%
    arrange(soybeanarea$State.ANSI, decreasing = FALSE)

soybeanarea$State.ANSI[1:134] <- paste0("0", soybeanarea$State.ANSI[1:134])

soybeanarea <- soybeanarea %>%
    arrange(soybeanarea$County.ANSI, decreasing = FALSE)

soybeanarea$County.ANSI[1:153]<- paste0("00", soybeanarea$County.ANSI[1:153])

soybeanarea$County.ANSI[154:1284]<- paste0("0", soybeanarea$County.ANSI[154:1284])

soybeanarea$GEOID <- paste(soybeanarea$State.ANSI, soybeanarea$County.ANSI, sep = "")

soybeanarea$soybean_acres<- as.numeric(as.character(soybeanarea$soybean_acres))

soybeanarea$soybean_acres[is.na(soybeanarea$soybean_acres)] <- 0

soybeanarea <- soybeanarea %>%
  dplyr::select(GEOID, soybean_acres)

soybeanarea <- soybeanarea %>%
  mutate(soybean_ha = soybean_acres*0.404686)

```

```{r}
peanutarea <- read.csv("~/Desktop/pig/21 crops/area/peanut_area.csv")

peanutarea <- peanutarea %>%
  dplyr::select(State.ANSI, County.ANSI, peanut_acres)

peanutarea <- peanutarea   %>%
    arrange(peanutarea$State.ANSI, decreasing = FALSE)

peanutarea$State.ANSI[1:65] <- paste0("0", peanutarea$State.ANSI[1:65])

peanutarea <- peanutarea %>%
    arrange(peanutarea$County.ANSI, decreasing = FALSE)

peanutarea$County.ANSI[1:25]<- paste0("00", peanutarea$County.ANSI[1:25])

peanutarea$County.ANSI[26:253]<- paste0("0", peanutarea$County.ANSI[26:253])

peanutarea$GEOID <- paste(peanutarea$State.ANSI, peanutarea$County.ANSI, sep = "")

peanutarea$peanut_acres<- as.numeric(as.character(peanutarea$peanut_acres))

peanutarea$peanut_acres[is.na(peanutarea$peanut_acres)] <- 0

peanutarea <- peanutarea %>%
  dplyr::select(GEOID, peanut_acres)

peanutarea<- peanutarea %>%
  mutate(peanut_ha = peanut_acres*0.404686)
```

```{r}
sugarbeetarea <- read.csv("~/Desktop/pig/21 crops/area/sugarbeet_area.csv")

sugarbeetarea <- sugarbeetarea[1:130,]

sugarbeetarea <- sugarbeetarea %>%
  dplyr::select(State.ANSI, County.ANSI, sugarbeet_acre)

sugarbeetarea <- sugarbeetarea   %>%
    arrange(sugarbeetarea$State.ANSI, decreasing = FALSE)

sugarbeetarea$State.ANSI[1:13] <- paste0("0", sugarbeetarea$State.ANSI[1:13])

sugarbeetarea <- sugarbeetarea %>%
    arrange(sugarbeetarea$County.ANSI, decreasing = FALSE)

sugarbeetarea$County.ANSI[1:10]<- paste0("00", sugarbeetarea$County.ANSI[1:10])

sugarbeetarea$County.ANSI[11:89]<- paste0("0", sugarbeetarea$County.ANSI[11:89])

sugarbeetarea$GEOID <- paste(sugarbeetarea$State.ANSI,sugarbeetarea$County.ANSI, sep = "")

sugarbeetarea$sugarbeet_acre<- as.numeric(as.character(sugarbeetarea$sugarbeet_acre))

sugarbeetarea$sugarbeet_acre[is.na(sugarbeetarea$sugarbeet_acre)] <- 0

sugarbeetarea <- sugarbeetarea %>%
  dplyr::select(GEOID, sugarbeet_acre)

sugarbeetarea<- sugarbeetarea %>%
  mutate(sugarbeet_ha = sugarbeet_acre*0.404686)
```

```{r}
sunflowerarea <- read.csv("~/Desktop/pig/21 crops/area/sunflower_area.csv")

sunflowerarea <- sunflowerarea %>%
  dplyr::select(State.ANSI, County.ANSI, sunflower_acres)

sunflowerarea <- sunflowerarea   %>%
    arrange(sunflowerarea$State.ANSI, decreasing = FALSE)

sunflowerarea$State.ANSI[1:47] <- paste0("0", sunflowerarea$State.ANSI[1:47])

sunflowerarea <- sunflowerarea %>%
    arrange(sunflowerarea$County.ANSI, decreasing = FALSE)

sunflowerarea$County.ANSI[1:46]<- paste0("00", sunflowerarea$County.ANSI[1:46])

sunflowerarea$County.ANSI[47:357]<- paste0("0", sunflowerarea$County.ANSI[47:357])

sunflowerarea$GEOID <- paste(sunflowerarea$State.ANSI,sunflowerarea$County.ANSI, sep = "")

sunflowerarea$sunflower_acres<- as.numeric(as.character(sunflowerarea$sunflower_acres))

sunflowerarea$sunflower_acres[is.na(sunflowerarea$sunflower_acres)] <- 0

sunflowerarea <- sunflowerarea %>%
  dplyr::select(GEOID, sunflower_acres)

sunflowerarea <- sunflowerarea %>%
  mutate(sunflower_ha = sunflower_acres*0.404686)
```

```{r}
potatoesarea <- read.csv("~/Desktop/pig/21 crops/area/potatoes_area.csv")

potatoesarea <- potatoesarea[1:2203, ]

potatoesarea <- potatoesarea %>%
  dplyr::select(State.ANSI, County.ANSI, potatoes_acres)

potatoesarea <- potatoesarea %>%
    arrange(potatoesarea$State.ANSI, decreasing = FALSE)

potatoesarea$State.ANSI[1:203] <- paste0("0", potatoesarea$State.ANSI[1:203])

potatoesarea <- potatoesarea %>%
    arrange(potatoesarea$County.ANSI, decreasing = FALSE)

potatoesarea$County.ANSI[1:182]<- paste0("00", potatoesarea$County.ANSI[1:182])

potatoesarea$County.ANSI[183:1395]<- paste0("0", potatoesarea$County.ANSI[183:1395])

potatoesarea$GEOID <- paste(potatoesarea$State.ANSI, potatoesarea$County.ANSI, sep = "")

potatoesarea$potatoes_acres <- as.numeric(as.character(potatoesarea$potatoes_acres))

potatoesarea$potatoes_acres[is.na(potatoesarea$potatoes_acres)] <- 0

potatoesarea <- potatoesarea %>%
  dplyr::select(GEOID, potatoes_acres)

potatoesarea <- potatoesarea %>%
  mutate(potatoes_ha = potatoes_acres*0.404686)
```

```{r}
canolaarea <- read.csv("~/Desktop/pig/21 crops/area/canola_area.csv")

canolaarea <- canolaarea[1:258, ]

canolaarea <- canolaarea %>%
  dplyr::select(State.ANSI, County.ANSI, canola_acre)

canolaarea <- canolaarea %>%
    arrange(canolaarea$State.ANSI, decreasing = FALSE)

canolaarea$State.ANSI[1:10] <- paste0("0", canolaarea$State.ANSI[1:10])

canolaarea <- canolaarea %>%
    arrange(canolaarea$County.ANSI, decreasing = FALSE)

canolaarea$County.ANSI[1:21]<- paste0("00", canolaarea$County.ANSI[1:21])

canolaarea$County.ANSI[22:193]<- paste0("0", canolaarea$County.ANSI[22:193])

canolaarea$GEOID <- paste(canolaarea$State.ANSI, canolaarea$County.ANSI, sep = "")

canolaarea$canola_acre <- as.numeric(as.character(canolaarea$canola_acre))

canolaarea$canola_acre[is.na(canolaarea$canola_acre)] <- 0

canolaarea <- canolaarea %>%
  dplyr::select(GEOID, canola_acre)

canolaarea  <- canolaarea  %>%
  mutate(canola_ha = canola_acre*0.404686)
```

```{r}
corngrainarea <- read.csv("~/Desktop/pig/21 crops/area/corn_grain_area.csv")

corngrainarea <- corngrainarea %>%
  dplyr::select(State.ANSI, County.ANSI, corn_grain_acre)

corngrainarea <- corngrainarea %>%
    arrange(corngrainarea$State.ANSI, decreasing = FALSE)

corngrainarea$State.ANSI[1:195] <- paste0("0", corngrainarea$State.ANSI[1:195])

corngrainarea <- corngrainarea %>%
    arrange(corngrainarea$County.ANSI, decreasing = FALSE)

corngrainarea$County.ANSI[1:192]<- paste0("00", corngrainarea$County.ANSI[1:192])

corngrainarea$County.ANSI[193:1604]<- paste0("0", corngrainarea$County.ANSI[193:1604])

corngrainarea$GEOID <- paste(corngrainarea$State.ANSI, corngrainarea$County.ANSI, sep = "")

corngrainarea$corn_grain_acre <- as.numeric(as.character(corngrainarea$corn_grain_acre))

corngrainarea$corn_grain_acre[is.na(corngrainarea$corn_grain_acre)] <- 0

corngrainarea <- corngrainarea %>%
  dplyr::select(GEOID, corn_grain_acre)

corngrainarea  <- corngrainarea  %>%
  mutate(corn_grain_ha = corn_grain_acre*0.404686)
```

```{r}
cornsilagearea <- read.csv("~/Desktop/pig/21 crops/area/corn_silage_area.csv")

cornsilagearea <- cornsilagearea %>%
  dplyr::select(State.ANSI, County.ANSI, corn_silage_acre)

cornsilagearea <- cornsilagearea %>%
    arrange(cornsilagearea$State.ANSI, decreasing = FALSE)

cornsilagearea$State.ANSI[1:128] <- paste0("0", cornsilagearea$State.ANSI[1:128])

cornsilagearea <- cornsilagearea %>%
    arrange(cornsilagearea$County.ANSI, decreasing = FALSE)

cornsilagearea$County.ANSI[1:181]<- paste0("00", cornsilagearea$County.ANSI[1:181])

cornsilagearea$County.ANSI[182:1339]<- paste0("0", cornsilagearea$County.ANSI[182:1339])

cornsilagearea$GEOID <- paste(cornsilagearea$State.ANSI, cornsilagearea$County.ANSI, sep = "")

cornsilagearea$corn_silage_acre <- as.numeric(as.character(cornsilagearea$corn_silage_acre ))

cornsilagearea$corn_silage_acre[is.na(cornsilagearea$corn_silage_acre)] <- 0

cornsilagearea <- cornsilagearea %>%
  dplyr::select(GEOID, corn_silage_acre)

cornsilagearea  <- cornsilagearea  %>%
  mutate(corn_silage_ha = corn_silage_acre*0.404686)
```

```{r}
tobaccoarea <- read.csv("~/Desktop/pig/21 crops/area/tobacco_area.csv")

tobaccoarea <- tobaccoarea %>%
  dplyr::select(State.ANSI, County.ANSI, tobacco_acre)

tobaccoarea <- tobaccoarea %>%
    arrange(tobaccoarea$State.ANSI, decreasing = FALSE)

tobaccoarea$State.ANSI[1:2] <- paste0("0", tobaccoarea$State.ANSI[1:2])

tobaccoarea <- tobaccoarea %>%
    arrange(tobaccoarea$County.ANSI, decreasing = FALSE)

tobaccoarea$County.ANSI[1:17]<- paste0("00", tobaccoarea$County.ANSI[1:17])

tobaccoarea$County.ANSI[18:172]<- paste0("0", tobaccoarea$County.ANSI[18:172])

tobaccoarea$GEOID <- paste(tobaccoarea$State.ANSI, tobaccoarea$County.ANSI, sep = "")

tobaccoarea$tobacco_acre <- as.numeric(as.character(tobaccoarea$tobacco_acre))

tobaccoarea$tobacco_acre[is.na(tobaccoarea$tobacco_acre)] <- 0

tobaccoarea <- tobaccoarea %>%
  dplyr::select(GEOID, tobacco_acre)

tobaccoarea <- tobaccoarea  %>%
  mutate(tobacco_ha = tobacco_acre*0.404686)
```

```{r}
alfalfarea <- read.csv("~/Desktop/pig/21 crops/area/alfalfa_area.csv")

alfalfarea <- alfalfarea[1:2688, ]

alfalfarea <- alfalfarea %>%
  dplyr::select(State.ANSI, County.ANSI, alfalfa_acres)

alfalfarea <- alfalfarea %>%
    arrange(alfalfarea$State.ANSI, decreasing = FALSE)

alfalfarea$State.ANSI[1:209] <- paste0("0", alfalfarea$State.ANSI[1:209])

alfalfarea <- alfalfarea %>%
    arrange(alfalfarea$County.ANSI, decreasing = FALSE)

alfalfarea$County.ANSI[1:215]<- paste0("00", alfalfarea$County.ANSI[1:215])

alfalfarea$County.ANSI[216:1672]<- paste0("0", alfalfarea$County.ANSI[216:1672])

alfalfarea$GEOID <- paste(alfalfarea$State.ANSI, alfalfarea$County.ANSI, sep = "")

alfalfarea$alfalfa_acres <- as.numeric(as.character(alfalfarea$alfalfa_acres))

alfalfarea$alfalfa_acres[is.na(alfalfarea$alfalfa_acres)] <- 0

alfalfarea <- alfalfarea %>%
  dplyr::select(GEOID, alfalfa_acres)

alfalfarea <- alfalfarea  %>%
  mutate(alfalfa_ha = alfalfa_acres*0.404686)
```

```{r}
hayarea <- read.csv("~/Desktop/pig/21 crops/area/hay_area.csv")

hayarea <- hayarea %>%
  dplyr::select(State.ANSI, County.ANSI, hay_acres)

hayarea <- hayarea %>%
    arrange(hayarea$State.ANSI, decreasing = FALSE)

hayarea$State.ANSI[1:286] <- paste0("0", hayarea$State.ANSI[1:286])

hayarea <- hayarea %>%
    arrange(hayarea$County.ANSI, decreasing = FALSE)

hayarea$County.ANSI[1:237]<- paste0("00", hayarea$County.ANSI[1:237])

hayarea$County.ANSI[238:1873]<- paste0("0", hayarea$County.ANSI[238:1873])

hayarea$GEOID <- paste(hayarea$State.ANSI, hayarea$County.ANSI, sep = "")

hayarea$hay_acres <- as.numeric(as.character(hayarea$hay_acres ))

hayarea$hay_acres [is.na(hayarea$hay_acres )] <- 0

hayarea <- hayarea %>%
  dplyr::select(GEOID, hay_acres)

hayarea <- hayarea  %>%
  mutate(hay_ha = hay_acres*0.404686)


```

```{r}
hayareaa <- merge(counties, hayarea, by = "GEOID", all.x = TRUE)

hayareaa_drop <- st_drop_geometry(hayareaa)

hayareaa_drop_alfalfa <- merge(hayareaa_drop, alfalfarea, by = "GEOID", all.x = TRUE)

hayareaa_drop_alfalfa$hay_ha[is.na(hayareaa_drop_alfalfa$hay_ha)] <- 0
hayareaa_drop_alfalfa$alfalfa_ha[is.na(hayareaa_drop_alfalfa$alfalfa_ha)] <- 0

hayareaa_drop_alfalfa <- hayareaa_drop_alfalfa %>%
  mutate(other_hay_ha = hay_ha -alfalfa_ha ) %>%
  dplyr::select(GEOID, other_hay_ha, alfalfa_ha)
```

```{r}
bc <- merge(barleyarea, cottonarea, by = "GEOID", all = TRUE)

wr <- merge(wheatarea, ricearea, by = "GEOID", all = TRUE)

bcwr <- merge(bc ,wr, by = "GEOID", all = TRUE)

sweetsoy <- merge(sweetcornarea, soybeanarea, by = "GEOID", all = TRUE)

ps <- merge(peanutarea, sugarbeetarea, by = "GEOID", all = TRUE)

sweetsoyps <- merge(sweetsoy, ps, by = "GEOID", all = TRUE)

bcwrsweetsoyps <- merge(bcwr, sweetsoyps, by = "GEOID", all = TRUE)

sp <- merge(sunflowerarea, potatoesarea, by = "GEOID", all = TRUE)

ca <- merge(canolaarea, alfalfarea, by = "GEOID", all = TRUE )

spca <- merge(sp, ca, by = "GEOID", all = TRUE)

bcwrsweetsoypsspca <- merge(bcwrsweetsoyps, spca, by = "GEOID", all = TRUE)

corntotal <- merge(corngrainarea, cornsilagearea, by = "GEOID", all = TRUE)

haytoba <- merge(hayareaa_drop_alfalfa, tobaccoarea, by = "GEOID", all = TRUE)

cornhay <- merge(corntotal,haytoba, by = "GEOID", all = TRUE )

bcwrsweetsoypsspca_cornhay <- merge(bcwrsweetsoypsspca, cornhay, by = "GEOID", all = TRUE)


bcwrsweetsoypsspca_cornhay2 <- merge(counties, bcwrsweetsoypsspca_cornhay, by = "GEOID", all.x = TRUE )

bcwrsweetsoypsspca_cornhay2_new <- bcwrsweetsoypsspca_cornhay2[!duplicated(bcwrsweetsoypsspca_cornhay2[ ,"GEOID", ]),]  # Delete rows

bcwrsweetsoypsspca_cornhay2_new[is.na(bcwrsweetsoypsspca_cornhay2_new)] <- 0

crop21_area <- st_drop_geometry(bcwrsweetsoypsspca_cornhay2_new)
 
crop21_area <- crop21_area %>%
    dplyr::select(GEOID, barley_ha, cotton_ha, wheat_ha, rice_ha, sweetcorn_ha, soybean_ha, peanut_ha, sugarbeet_ha, sunflower_ha,potatoes_ha, canola_ha,alfalfa_ha.x,other_hay_ha, corn_grain_ha, corn_silage_ha,tobacco_ha)


crop17 <- crop17 %>%
  mutate(sugarcane_ha = (sugarcane_TgN1/sum(sugarcane_TgN1, na.rm = TRUE))*365807 ) %>%
  mutate(drybeans_ha = (drybeans_TgN1/sum(drybeans_TgN1, na.rm = TRUE))*594332 ) %>%
  mutate(sorghum_ha = (sorghum_TgN1/sum(sorghum_TgN1, na.rm = TRUE))*2051565) %>%
  mutate(apple_ha = (apples_TgN1/sum(apples_TgN1, na.rm = TRUE))*132820) %>%
  mutate(orange_ha = (oranges_TgN1/sum(oranges_TgN1, na.rm = TRUE))*213470) %>%
  mutate(barley_ha1 = (barley_TgN1/sum(barley_TgN1, na.rm = TRUE))*790755) %>%
  mutate(potato_ha1 =  (potatoes_TgN1/sum(potatoes_TgN1, na.rm = TRUE))*422491)

crop17 <- merge(crop17,crop21_area, by = "GEOID" )
  
crop17 <- crop17 %>%
  mutate(crop21har = (barley_ha1 + cotton_ha +wheat_ha+ rice_ha +  sweetcorn_ha + soybean_ha + peanut_ha + sugarbeet_ha + sunflower_ha + potato_ha1 +canola_ha + alfalfa_ha.x+ other_hay_ha + corn_grain_ha + corn_silage_ha + tobacco_ha + sugarcane_ha + drybeans_ha + sorghum_ha + apple_ha + orange_ha))

sum(crop17$crop21har, na.rm = TRUE)



```



```{r}
irri15 <- read.csv("~/Desktop/revised manure sur/irrigation_conu.csv")

irri15$FIPS[1:316] <- paste0("0", irri15$FIPS[1:316])

irri15 <- irri15 %>%
  rename(GEOID = FIPS)

crop17 <- merge(crop17, irri15, by = "GEOID", all.x = TRUE)

crop17 <- crop17 %>%
  mutate(irriga_new = (IR.WFrTo/sum(IR.WFrTo, na.rm = TRUE))* 0.16)


```


```{r}
crop17 <- crop17 %>%
  mutate(dep =crop21har*7.1336/10^9) %>%
  mutate(exisN = peanut_TgN1 + alfal_TgN1 +  soybean_TgN1 + irriga_new +dep )

```

```{r}
c1c2 <- crop17 %>%
  dplyr::select(GEOID, exisN, crop21_current, crop21_NUE80) %>%
  mutate(C1= crop21_current - crop21_NUE80) 
```


```{r}
crop_manure <- merge(crop_manure, c1c2, by = "GEOID", all = TRUE)

crop_manure[is.na(crop_manure)] <- 0
```

```{r}

##-----------------------------------------

crop_manure$M1[crop_manure$M1 < 0] <- 0 

crop_manure <- crop_manure %>%
  mutate(ext = crop21_current - exisN)

crop_manure$ext[crop_manure$ext < 0] <- 0

crop_manure <- crop_manure %>%
  mutate(ext80 = crop21_NUE80 - exisN)

crop_manure$ext80[crop_manure$ext80 < 0] <- 0

crop_manure <- crop_manure %>%
  mutate(mansur1 = applied_manure_re - (ext)) %>%
  mutate(mansur2 = M1+applied_manure_re - (ext)) %>%
  mutate(mansur3 = M2 + M1+applied_manure_re - (ext) ) %>%
  mutate(mansur4 = M2 + M1+applied_manure_re - (ext80)) %>%
  mutate(mansur1gg = mansur1*1000) %>%
  mutate(mansur2gg = mansur2*1000) %>%
  mutate(mansur3gg = mansur3*1000) %>%
  mutate(mansur4gg = mansur4*1000) 

```



```{r}
crop_manure_map <-st_as_sf(crop_manure)

pal7 <- c("#01665E", "#35978F" ,"#80CDC1", "#C7EAE5","#DFC27D")

crop_manure_map %>%
  filter(mansur1gg== 0)

tmap_mode("plot")

tm_shape(crop_manure_map) +
  tm_fill("mansur1gg",title="Gg N", breaks = c(-55, -10, -5, -1, 0, 70), labels = c("-55 to -10", "-10 to -5", "-5 to -1", "-1 to 0", "> 0"), palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 

 
tm_shape(crop_manure_map) +
  tm_fill("mansur2gg",title="Gg N", breaks = c(-55, -10, -5, -1, 0, 70), labels = c("-55 to -10", "-10 to -5", "-5 to -1", "-1 to 0", "0 to 70"),palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
 

tm_shape(crop_manure_map) +
  tm_fill("mansur3gg",title="Gg N", breaks = c(-55, -10, -5, -1, 0, 70), labels = c("-55 to -10", "-10 to -5", "-5 to -1", "-1 to 0", "0 to 70"),palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
 
 
tm_shape(crop_manure_map) +
  tm_fill("mansur4gg",title="Gg N", breaks = c(-55, -10, -5, -1, 0, 70), labels = c("-55 to -10", "-10 to -5", "-5 to -1", "-1 to 0", "> 0"),palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 


crop_manure_map <- crop_manure_map %>%
  mutate(m1gg = M1*1000) %>%
  mutate(m2gg = M2*1000) %>%
  mutate(c1gg = C1*1000) 
  
  
tm_shape(crop_manure_map) +
  tm_fill("m1gg",title="Gg N", breaks = c(0, 0.005, 0.2, 1, 5, 20), labels = c("0 to 0.005", "0.005 to 0.2", "0.2 to 1", "1 to 5", "5 to 20"), palette=get_brewer_pal(palette="YlOrBr", n = 5, plot = FALSE), colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
 
 
tm_shape(crop_manure_map) +
  tm_fill("m2gg",title="Gg N", breaks = c(0, 0.005, 0.2, 1, 5, 70), labels = c("0 to 0.005", "0.005 to 0.2", "0.2 to 1", "1 to 5", "5 to 70"), palette=get_brewer_pal(palette="YlOrBr", n = 5, plot = FALSE), colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 


tm_shape(crop_manure_map) +
  tm_fill("c1gg",title="Gg N", breaks = c(0, 0.02, 0.1, 0.5, 1, 25), labels= c("0 to 0.02", "0.02 to 0.1", "0.1 to 0.5", "0.5 to 1", "1 to 25"), palette=get_brewer_pal(palette="GnBu", n = 5, plot = FALSE), colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
 

```

##one county example (Mountrail, ND)
```{r}
GA_sample_county <- crop_manure_map %>%
  filter(GEOID == "38061") %>%
  mutate(mansur1gg = mansur1*10^3) %>%
  mutate(mansur2gg = M1*10^3) %>%
  mutate(mansur3gg = M2*10^3) %>%
  mutate(mansur4gg = C1*10^3) %>%
  dplyr::select(GEOID, mansur1gg, mansur2gg, mansur3gg, mansur4gg)

GA_df <- data.frame(
  group = c('Baseline','M1','M2','iNUE'),
  value = c(GA_sample_county$mansur1gg, GA_sample_county$mansur2gg, GA_sample_county$mansur3gg, GA_sample_county$mansur4gg)
)

GA_df$value <- round(GA_df$value, digits=1)

waterfall(GA_df, fill_by_sign = FALSE, fill_colours = c("#D2B48C", "#CC9900", "#996600", "#009933"),calc_total = TRUE, total_rect_color = "#FDF5E6", total_rect_text_color = "black", rect_text_size = 2, total_axis_text = "Outcome" ) + 
  labs(title="", 
         x="", y = "Manure surplus (Mg N)") +
  theme_bw() +
    theme( 
         axis.text.y = element_text(size = 15),
        axis.title.y  = element_text(size = 15),
       axis.text.x = element_text(size = 15) ) 

##---------------------------------------- use fertilizer as y axis 
fer17 <- read.csv("~/Desktop/pig/21 crops/farm_fer_17.csv")

fer17$GEOID[1:285]<- paste0("0", fer17$GEOID[1:285])

fer17 <- fer17 %>%
  mutate(ferton = farmfertN.kg.2017/10^6) %>%
  dplyr::select(GEOID, ferton)

GA_sample_county <- merge(GA_sample_county, fer17, by = "GEOID", all.x = TRUE)


GA_df <- data.frame(
  group = c('Baseline','M1','M2','iNUE'),
  value = c(GA_sample_county$ferton, -GA_sample_county$mansur2gg, -GA_sample_county$mansur3gg, -GA_sample_county$mansur4gg)
)

GA_df$value <- round(GA_df$value, digits=1)

waterfall(GA_df, fill_by_sign = FALSE,  fill_colours = c("#D2B48C", "#CC9900", "#996600", "#009933"), calc_total = TRUE, total_rect_color = "#FDF5E6", total_rect_text_color = "black", rect_text_size = 2, total_axis_text = "Outcome" ) + 
  labs(title="", 
         x="", y = "Synthetic fertilizer inputs (Mg N)") +
  theme_bw() +
    theme( 
         axis.text.y = element_text(size = 15),
        axis.title.y  = element_text(size = 15),
       axis.text.x = element_text(size = 15) ) 

```








