---
title: "manurePbalance"
author: "yanyu wang"
date: "2025-06-20"
output: html_document
---

```{r}
library(ggplot2)
library(raster)
library(dplyr)
library(sf)
library(tmap)
library(tmaptools)
tmap_mode("plot")
library(RColorBrewer)
library(cluster)
library(factoextra)
library(gridExtra)
library(writexl)
library(openxlsx)
library(readxl)
library(writexl)
library(waterfalls)
library(ggthemes)
```


## phosphrous MANURE CALCULATION

## county-level analyses 
```{r}
beef17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/cattle_onfeed_sales.csv")

beef17_sales <- beef17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

beef17_sales$State.ANSI[1:95] <- paste0("0", beef17_sales$State.ANSI[1:95])

beef17_sales <- beef17_sales %>%
    arrange(beef17_sales$County.ANSI, decreasing = FALSE)

beef17_sales$County.ANSI[1:143]<- paste0("00", beef17_sales$County.ANSI[1:143])

beef17_sales$County.ANSI[144:1214]<- paste0("0", beef17_sales$County.ANSI[144:1214])

beef17_sales$GEOID <- paste(beef17_sales$State.ANSI, beef17_sales$County.ANSI, sep = "")

beef17_sales$Value<- as.numeric(as.character(beef17_sales$Value))

beef17_sales$Value[is.na(beef17_sales$Value)] <- 0

beef17_sales <- beef17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)
```

```{r}
beef17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/cattle_onfeed_inven.csv")

beef17_inven <- beef17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

beef17_inven$State.ANSI[1:66] <- paste0("0", beef17_inven$State.ANSI[1:66])

beef17_inven <- beef17_inven %>%
    arrange(beef17_inven$County.ANSI, decreasing = FALSE)

beef17_inven$County.ANSI[1:122]<- paste0("00", beef17_inven$County.ANSI[1:122])

beef17_inven$County.ANSI[123:1034]<- paste0("0", beef17_inven$County.ANSI[123:1034])

beef17_inven$GEOID <- paste(beef17_inven$State.ANSI, beef17_inven$County.ANSI, sep = "")

beef17_inven$Value<- as.numeric(as.character(beef17_inven$Value))

beef17_inven$Value[is.na(beef17_inven$Value)] <- 0

beef17_inven <- beef17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(beef17_inven$inventory)
```




```{r}
beef <- merge(beef17_inven, beef17_sales, by = "GEOID", all = TRUE)
beef[is.na(beef)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
beef <- beef %>%
  mutate(man_beef = (((inventory*1/2.5)+(sales/2.5*(2.5-1)/2.5))*(1/1.02))*7.10775/10^9) %>%
  dplyr::select(GEOID, man_beef)

sum(beef$man_beef)

str(beef)
```



```{r}
milk17 <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/milk_inven.csv")

milk17 <- milk17 %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

milk17$State.ANSI[1:215] <- paste0("0", milk17$State.ANSI[1:215])

milk17 <- milk17 %>%
    arrange(milk17$County.ANSI, decreasing = FALSE)

milk17$County.ANSI[1:198]<- paste0("00", milk17$County.ANSI[1:198])

milk17$County.ANSI[199:1546]<- paste0("0", milk17$County.ANSI[199:1546])

milk17$GEOID <- paste(milk17$State.ANSI, milk17$County.ANSI, sep = "")

milk17$Value<- as.numeric(as.character(milk17$Value))

milk17$Value[is.na(milk17$Value)] <- 0

milk17 <- milk17 %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)


milk17 <- milk17 %>%
  mutate(man_milk =inventory*(1/0.73)*21.0519/10^9) %>%
  dplyr::select(GEOID, man_milk)

sum(milk17$man_milk)

cattle<- merge(beef, milk17, by = "GEOID", all = TRUE)
```


```{r}
milk17 <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/milk_inven.csv")

milk17 <- milk17 %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

milk17$State.ANSI[1:215] <- paste0("0", milk17$State.ANSI[1:215])

milk17 <- milk17 %>%
    arrange(milk17$County.ANSI, decreasing = FALSE)

milk17$County.ANSI[1:198]<- paste0("00", milk17$County.ANSI[1:198])

milk17$County.ANSI[199:1546]<- paste0("0", milk17$County.ANSI[199:1546])

milk17$GEOID <- paste(milk17$State.ANSI, milk17$County.ANSI, sep = "")

milk17$Value<- as.numeric(as.character(milk17$Value))

milk17$Value[is.na(milk17$Value)] <- 0

milk17 <- milk17 %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)


##milk17 <- milk17 %>%
##  mutate(man_milk =inventory*(1/0.73)*118.25676/10^9) %>%
##  dplyr::select(GEOID, man_milk)

##sum(milk17$man_milk)

```



```{r}
milk17farm <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/milkcowfarm.csv")

milk17farm <- milk17farm %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

milk17farm$State.ANSI[1:219] <- paste0("0", milk17farm$State.ANSI[1:219])

milk17farm <- milk17farm %>%
    arrange(milk17farm$County.ANSI, decreasing = FALSE)

milk17farm$County.ANSI[1:201]<- paste0("00", milk17farm$County.ANSI[1:201])

milk17farm$County.ANSI[202:1549]<- paste0("0", milk17farm$County.ANSI[202:1549])

milk17farm$GEOID <- paste(milk17farm$State.ANSI, milk17farm$County.ANSI, sep = "")

milk17farm$Value<- as.numeric(as.character(milk17farm$Value))

milk17farm$Value[is.na(milk17farm$Value)] <- 0

milk17farm <-milk17farm %>%
  dplyr::select(GEOID, Value) %>%
  rename(farm = Value)

  
```

```{r}
milk17 <- merge(milk17, milk17farm, by = "GEOID")

milk17 <- milk17 %>%
  mutate(herd = inventory/farm)

```




```{r}
library(dplyr)

# Step 1: Create category and assign pasture %
milk17_pasture <- milk17 %>%
  mutate(
    herd_cat = case_when(
      herd < 30 ~ "very_small",
      herd >= 30 & herd < 100 ~ "small",
      herd >= 100 & herd < 500 ~ "medium",
      herd >= 500 ~ "large"
    ),
    pasture_pct = case_when(
      herd_cat == "very_small" ~ 17.6,
      herd_cat == "small" ~ 5.8,
      herd_cat == "medium" ~ 8.0,
      herd_cat == "large" ~ 1.5
    )
  )

# Step 2: Calculate weighted pasture percentage (weighted by inventory)
weighted_pasture_pct <- milk17_pasture %>%
  summarise(weighted_avg = sum(pasture_pct * inventory) / sum(inventory)) %>%
  pull(weighted_avg)

# Output result
print(paste("Weighted average pasture percentage:", round(weighted_pasture_pct, 2), "%"))

```




```{r}
milk17_pasture<- milk17_pasture %>%
  mutate(man_milk =(inventory*(1/0.73)*21.0519/10^9)) %>%
  mutate(man_milk_withoutpas = man_milk*(1-pasture_pct/100)) 

sum(milk17_pasture$man_milk_withoutpas)
```


```{r}
pastureland17 <- read.csv("~/Desktop/local /pastureland17.csv")

pastureland17 <- pastureland17 %>%
  dplyr::select(State.ANSI, County.ANSI, pastureland_acres)

pastureland17$State.ANSI[1:290] <- paste0("0", pastureland17$State.ANSI[1:290])

pastureland17 <- pastureland17 %>%
    arrange(pastureland17$County.ANSI, decreasing = FALSE)

pastureland17$County.ANSI[1:240]<- paste0("00", pastureland17$County.ANSI[1:240])

pastureland17$County.ANSI[241:1889]<- paste0("0", pastureland17$County.ANSI[241:1889])

pastureland17$GEOID <- paste(pastureland17$State.ANSI, pastureland17$County.ANSI, sep = "")

pastureland17$pastureland_acres <- as.numeric(as.character(pastureland17$pastureland_acres))

pastureland17$pastureland_acres[is.na(pastureland17$pastureland_acres)] <- 0

pastureland17 <- pastureland17 %>%
  dplyr::select(GEOID, pastureland_acres)
```


```{r}
milk17_pasture <- merge(milk17_pasture, pastureland17, by = "GEOID")


milk17_pasture <- milk17_pasture %>%
  mutate(pasture_pct = ifelse(pastureland_acres == 0, 0, pasture_pct))


milk17_pasture<- milk17_pasture %>%
  mutate(man_milk_withoutpas = man_milk*(1-pasture_pct/100)) 

sum(milk17_pasture$man_milk_withoutpas)

milk17_pasture<- milk17_pasture %>%
  dplyr::select(GEOID, man_milk_withoutpas, man_milk)

cattle<- merge(beef, milk17_pasture, by = "GEOID", all = TRUE)

```

```{r}
hog17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/hog_inven_new.csv")

hog17_inven <- hog17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

hog17_inven$State.ANSI[1:264] <- paste0("0", hog17_inven$State.ANSI[1:264])

hog17_inven <- hog17_inven %>%
    arrange(hog17_inven$County.ANSI, decreasing = FALSE)

hog17_inven$County.ANSI[1:232]<- paste0("00", hog17_inven$County.ANSI[1:232])

hog17_inven$County.ANSI[233:1789]<- paste0("0", hog17_inven$County.ANSI[233:1789])

hog17_inven$GEOID <- paste(hog17_inven$State.ANSI, hog17_inven$County.ANSI, sep = "")

hog17_inven$Value<- as.numeric(as.character(hog17_inven$Value))

hog17_inven$Value[is.na(hog17_inven$Value)] <- 0

hog17_inven <- hog17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(hog17_inven$inventory)
```



```{r}
hog17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/hog_sales.csv")

hog17_sales <- hog17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

hog17_sales$State.ANSI[1:257] <- paste0("0", hog17_sales$State.ANSI[1:257])

hog17_sales <- hog17_sales %>%
    arrange(hog17_sales$County.ANSI, decreasing = FALSE)

hog17_sales$County.ANSI[1:223]<- paste0("00", hog17_sales$County.ANSI[1:223])

hog17_sales$County.ANSI[224:1759]<- paste0("0", hog17_sales$County.ANSI[224:1759])

hog17_sales$GEOID <- paste(hog17_sales$State.ANSI, hog17_sales$County.ANSI, sep = "")

hog17_sales$Value<- as.numeric(as.character(hog17_sales$Value))

hog17_sales$Value[is.na(hog17_sales$Value)] <- 0

hog17_sales <- hog17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(hog17_sales$sales)
```

```{r}
hog <- merge(hog17_inven, hog17_sales, by = "GEOID", all = TRUE)
hog[is.na(hog)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
hog <- hog %>%
  mutate(hog_inven_breed = inventory * 0.08) %>%
  mutate(hog_inven_finishonly = inventory * 0.43) %>%
  mutate(hog_inven_farrowfinish = inventory*0.28) %>%
  mutate(hog_inven_farrowtofeed = inventory * 0.01) %>%
  mutate(hog_inven_farrowtowean = inventory * 0.13) %>%
  mutate(hog_inven_nursery = sales*0.07) %>%
  mutate(hog_sales_finishonly = sales * 0.33) %>%
  mutate(hog_sales_farrowfinish = sales*0.23) %>%
  mutate(hog_sales_farrowtofeed = sales * 0.02) %>%
  mutate(hog_sales_farrowtowean = sales * 0.31) %>%
  mutate(hog_sales_nursery = inventory*0.11) %>%
  mutate(man_hog_breed_N = ( hog_inven_breed*(1/2.27)*32.39298/10^9  )) %>%
  mutate(man_hog_finishonly_N = (hog_inven_finishonly*(1/2.6) + (hog_sales_finishonly/2.6 * ((2.6-1)/2.6)))*1/6.7*87.291/10^9 ) %>%
  mutate(man_hog_farrowfinish_N = (hog_inven_farrowfinish*(1/2) + (hog_sales_farrowfinish/2 * ((2-1)/2)))*1/7.4*108.43875/10^9 ) %>%
  mutate(man_hog_farrowtofeed_N = (hog_inven_farrowtofeed*(1/8) + (hog_sales_farrowtofeed/8 * ((8-1)/8)))*1/50*148.89825/10^9 ) %>%
  mutate(man_hog_farrowtowean_N = (hog_inven_farrowtowean*(1/18) + (hog_sales_farrowtowean/18 * ((18-1)/18)))*1/143*149.8095/10^9 ) %>%
  mutate(man_hog_nursery_N = (hog_inven_nursery*(1/13) + (hog_sales_nursery/13 * ((13-1)/13)))*1/37*148.716/10^9 ) %>%
  mutate(man_hog_N = man_hog_breed_N + man_hog_farrowfinish_N + man_hog_farrowtofeed_N + man_hog_farrowfinish_N + man_hog_finishonly_N + man_hog_nursery_N) %>%
  mutate(man_hog_breed_P = ( inventory*(1/2.27)*9.70821/10^9  )) %>%
  mutate(man_hog_finishonly_P = (hog_inven_finishonly*(1/2.6) + (hog_sales_finishonly/2.6 * ((2.6-1)/2.6)))*1/6.7*14.3838/10^9 ) %>%
  mutate(man_hog_farrowfinish_P = (hog_inven_farrowfinish*(1/2) + (hog_sales_farrowfinish/2 * ((2-1)/2)))*1/7.4*17.01/10^9 ) %>%
  mutate(man_hog_farrowtofeed_P = (hog_inven_farrowtofeed*(1/8) + (hog_sales_farrowtofeed/8 * ((8-1)/8)))*1/50*23.8545/10^9 ) %>%
  mutate(man_hog_farrowtowean_P = (hog_inven_farrowtowean*(1/18) + (hog_sales_farrowtowean/18 * ((18-1)/18)))*1/143*23.9841/10^9 ) %>%
  mutate(man_hog_nursery_P = (hog_inven_nursery*(1/13) + (hog_sales_nursery/13 * ((13-1)/13)))*1/37*23.8383/10^9 ) %>%
  mutate(man_hog_P = man_hog_breed_P + man_hog_farrowfinish_P + man_hog_farrowtofeed_P + man_hog_farrowfinish_P + man_hog_finishonly_P + man_hog_nursery_P) %>%
  mutate(manhog_N_inven = ( hog_inven_breed*(1/2.27)*32.39298/10^9  + hog_inven_finishonly*(1/2.6)*1/6.7*87.291/10^9 + hog_inven_farrowfinish*(1/2)*1/7.4*108.43875/10^9 + 
                                                                                                                   hog_inven_farrowtofeed*(1/8)* 1/143*149.8095/10^9 +hog_inven_farrowtowean*(1/18*1/143*149.8095/10^9) + hog_inven_nursery*(1/13)*1/37*148.716/10^9  )) %>%
  mutate(manhog_N_sales = man_hog_N - manhog_N_inven) %>%
    mutate(manhog_P_inven = ( hog_inven_breed*(1/2.27)*9.70821/10^9  + hog_inven_finishonly*(1/2.6)*1/6.7*14.3838/10^9 + hog_inven_farrowfinish*(1/2)*1/7.4*17.01/10^9 + 
                                                                                                                   hog_inven_farrowtofeed*(1/8)* 1/143*23.8545/10^9 +hog_inven_farrowtowean*(1/18*1/143*23.9841/10^9) + hog_inven_nursery*(1/13)*1/37*23.8383/10^9  )) %>%
  mutate(manhog_P_sales = man_hog_P - manhog_P_inven) %>%
  dplyr::select(GEOID, man_hog_N, manhog_N_inven, manhog_N_sales,man_hog_P , manhog_P_inven, manhog_P_sales)

sum(hog$man_hog_N)

sum(hog$manhog_N_inven)

sum(hog$manhog_N_sales)

sum(hog$man_hog_P)

sum(hog$manhog_P_inven)

sum(hog$manhog_P_sales)

```




```{r}
broiler17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/broiler_inven.csv")

broiler17_inven <- broiler17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

broiler17_inven$State.ANSI[1:250] <- paste0("0", broiler17_inven$State.ANSI[1:250])

broiler17_inven <- broiler17_inven %>%
    arrange(broiler17_inven$County.ANSI, decreasing = FALSE)

broiler17_inven$County.ANSI[1:210]<- paste0("00", broiler17_inven$County.ANSI[1:210])

broiler17_inven$County.ANSI[211:1643]<- paste0("0", broiler17_inven$County.ANSI[211:1643])

broiler17_inven$GEOID <- paste(broiler17_inven$State.ANSI, broiler17_inven$County.ANSI, sep = "")

broiler17_inven$Value<- as.numeric(as.character(broiler17_inven$Value))

broiler17_inven$Value[is.na(broiler17_inven$Value)] <- 0

broiler17_inven <- broiler17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(broiler17_inven$inventory)
```


```{r}
broiler17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/broiler_sales.csv")

broiler17_sales <- broiler17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

broiler17_sales$State.ANSI[1:226] <- paste0("0", broiler17_sales$State.ANSI[1:226])

broiler17_sales <- broiler17_sales %>%
    arrange(broiler17_sales$County.ANSI, decreasing = FALSE)

broiler17_sales$County.ANSI[1:186]<- paste0("00", broiler17_sales$County.ANSI[1:186])

broiler17_sales$County.ANSI[187:1448]<- paste0("0", broiler17_sales$County.ANSI[187:1448])

broiler17_sales$GEOID <- paste(broiler17_sales$State.ANSI, broiler17_sales$County.ANSI, sep = "")

broiler17_sales$Value<- as.numeric(as.character(broiler17_sales$Value))

broiler17_sales$Value[is.na(broiler17_sales$Value)] <- 0

broiler17_sales <- broiler17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(broiler17_sales$sales)
```



```{r}
broiler <- merge(broiler17_inven, broiler17_sales, by = "GEOID", all = TRUE)
broiler[is.na(broiler)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
broiler <- broiler %>%
  mutate(man_broiler = (((inventory*1/6)+(sales/6*(6-1)/6))*(1/382)*45.346815/10^9) ) %>%
  dplyr::select(GEOID, man_broiler)

sum(broiler$man_broiler)
```

```{r}
layer17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/layer_inven.csv")

layer17_inven <- layer17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

layer17_inven$State.ANSI[1:283] <- paste0("0", layer17_inven$State.ANSI[1:283])

layer17_inven <- layer17_inven %>%
    arrange(layer17_inven$County.ANSI, decreasing = FALSE)

layer17_inven$County.ANSI[1:236]<- paste0("00", layer17_inven$County.ANSI[1:236])

layer17_inven$County.ANSI[237:1868]<- paste0("0", layer17_inven$County.ANSI[237:1868])

layer17_inven$GEOID <- paste(layer17_inven$State.ANSI, layer17_inven$County.ANSI, sep = "")

layer17_inven$Value<- as.numeric(as.character(layer17_inven$Value))

layer17_inven$Value[is.na(layer17_inven$Value)] <- 0

layer17_inven <- layer17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(layer17_inven$inventory)
```


```{r}
layer17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/layer_sales.csv")

layer17_sales <- layer17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

layer17_sales$State.ANSI[1:253] <- paste0("0", layer17_sales$State.ANSI[1:253])

layer17_sales <- layer17_sales %>%
    arrange(layer17_sales$County.ANSI, decreasing = FALSE)

layer17_sales$County.ANSI[1:210]<- paste0("00", layer17_sales$County.ANSI[1:210])

layer17_sales$County.ANSI[211:1629]<- paste0("0", layer17_sales$County.ANSI[211:1629])

layer17_sales$GEOID <- paste(layer17_sales$State.ANSI, layer17_sales$County.ANSI, sep = "")

layer17_sales$Value<- as.numeric(as.character(layer17_sales$Value))

layer17_sales$Value[is.na(layer17_sales$Value)] <- 0

layer17_sales <- layer17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(layer17_sales$sales)
```


```{r}
layer <- merge(layer17_inven, layer17_sales, by = "GEOID", all = TRUE)
layer[is.na(layer)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
layer <- layer %>%
  mutate(man_layer = (inventory)*(1/293)*59.917095/10^9 ) %>%
  dplyr::select(GEOID, man_layer)

sum(layer$man_layer)
```


```{r}
pullet17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/pullet_inven.csv")

pullet17_inven <- pullet17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

pullet17_inven$State.ANSI[1:247] <- paste0("0", pullet17_inven$State.ANSI[1:247])

pullet17_inven <- pullet17_inven %>%
    arrange(pullet17_inven$County.ANSI, decreasing = FALSE)

pullet17_inven$County.ANSI[1:216]<- paste0("00", pullet17_inven$County.ANSI[1:216])

pullet17_inven$County.ANSI[217:1639]<- paste0("0", pullet17_inven$County.ANSI[217:1639])

pullet17_inven$GEOID <- paste(pullet17_inven$State.ANSI, pullet17_inven$County.ANSI, sep = "")

pullet17_inven$Value<- as.numeric(as.character(pullet17_inven$Value))

pullet17_inven$Value[is.na(pullet17_inven$Value)] <- 0

pullet17_inven <- pullet17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(pullet17_inven$inventory)
```





```{r}
pullet17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/pullet_sales.csv")

pullet17_sales <- pullet17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

pullet17_sales$State.ANSI[1:147] <- paste0("0", pullet17_sales$State.ANSI[1:147])

pullet17_sales <- pullet17_sales %>%
    arrange(pullet17_sales$County.ANSI, decreasing = FALSE)

pullet17_sales$County.ANSI[1:101]<- paste0("00", pullet17_sales$County.ANSI[1:101])

pullet17_sales$County.ANSI[102:815]<- paste0("0", pullet17_sales$County.ANSI[102:815])

pullet17_sales$GEOID <- paste(pullet17_sales$State.ANSI, pullet17_sales$County.ANSI, sep = "")

pullet17_sales$Value<- as.numeric(as.character(pullet17_sales$Value))

pullet17_sales$Value[is.na(pullet17_sales$Value)] <- 0

pullet17_sales <- pullet17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(pullet17_sales$sales)
```

```{r}
pullet <- merge(pullet17_inven, pullet17_sales, by = "GEOID", all = TRUE)
pullet[is.na(pullet)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
pullet <- pullet %>%
  mutate(man_pullet  = (((inventory*1/2.25)+(sales/2.25*(2.25-1)/2.25))*(1/350))/10^9*38.903085) %>%
  dplyr::select(GEOID, man_pullet)

sum(pullet$man_pullet)
```






```{r}
turkey17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/turkey_inven.csv")

turkey17_inven <- turkey17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

turkey17_inven$State.ANSI[1:219] <- paste0("0", turkey17_inven$State.ANSI[1:219])

turkey17_inven <- turkey17_inven %>%
    arrange(turkey17_inven$County.ANSI, decreasing = FALSE)

turkey17_inven$County.ANSI[1:195]<- paste0("00", turkey17_inven$County.ANSI[1:195])

turkey17_inven$County.ANSI[196:1475]<- paste0("0", turkey17_inven$County.ANSI[196:1475])

turkey17_inven$GEOID <- paste(turkey17_inven$State.ANSI, turkey17_inven$County.ANSI, sep = "")

turkey17_inven$Value<- as.numeric(as.character(turkey17_inven$Value))

turkey17_inven$Value[is.na(turkey17_inven$Value)] <- 0

turkey17_inven <- turkey17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(turkey17_inven$inventory)
```


```{r}
turkey17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/turkey_sales.csv")

turkey17_sales <- turkey17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

turkey17_sales$State.ANSI[1:161] <- paste0("0", turkey17_sales$State.ANSI[1:161])

turkey17_sales <- turkey17_sales %>%
    arrange(turkey17_sales$County.ANSI, decreasing = FALSE)

turkey17_sales$County.ANSI[1:150]<- paste0("00", turkey17_sales$County.ANSI[1:150])

turkey17_sales$County.ANSI[151:1113]<- paste0("0", turkey17_sales$County.ANSI[151:1113])

turkey17_sales$GEOID <- paste(turkey17_sales$State.ANSI, turkey17_sales$County.ANSI, sep = "")

turkey17_sales$Value<- as.numeric(as.character(turkey17_sales$Value))

turkey17_sales$Value[is.na(turkey17_sales$Value)] <- 0

turkey17_sales <- turkey17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(turkey17_sales$sales)
```



```{r}
turkey <- merge(turkey17_inven, turkey17_sales, by = "GEOID", all = TRUE)
turkey[is.na(turkey)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
turkey <- turkey %>%
  mutate(man_turkey  = inventory*1/(50)* 32.40486/10^9 + ((sales/2*(2-1)/2))*(1/59)*29.13678/10^9 ) %>%
  dplyr::select(GEOID, man_turkey)

sum(turkey$man_turkey)
```


```{r}
duck17_inven <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/duck_inven.csv")

duck17_inven <- duck17_inven %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

duck17_inven$State.ANSI[1:236] <- paste0("0", duck17_inven$State.ANSI[1:236])

duck17_inven <- duck17_inven %>%
    arrange(duck17_inven$County.ANSI, decreasing = FALSE)

duck17_inven$County.ANSI[1:206]<- paste0("00", duck17_inven$County.ANSI[1:206])

duck17_inven$County.ANSI[207:1610]<- paste0("0", duck17_inven$County.ANSI[207:1610])

duck17_inven$GEOID <- paste(duck17_inven$State.ANSI, duck17_inven$County.ANSI, sep = "")

duck17_inven$Value<- as.numeric(as.character(duck17_inven$Value))

duck17_inven$Value[is.na(duck17_inven$Value)] <- 0

duck17_inven <- duck17_inven %>%
  dplyr::select(GEOID, Value) %>%
  rename(inventory = Value)

sum(duck17_inven$inventory)
```





```{r}
duck17_sales <- read.csv("~/Desktop/revised manure sur/renamed files_crop /livestock_county_withoutHIAL/duck_sales.csv")

duck17_sales <- duck17_sales %>%
  dplyr::select(State.ANSI, County.ANSI, State, Value)

duck17_sales$State.ANSI[1:136] <- paste0("0", duck17_sales$State.ANSI[1:136])

duck17_sales <- duck17_sales %>%
    arrange(duck17_sales$County.ANSI, decreasing = FALSE)

duck17_sales$County.ANSI[1:130]<- paste0("00", duck17_sales$County.ANSI[1:130])

duck17_sales$County.ANSI[131:974]<- paste0("0", duck17_sales$County.ANSI[131:974])

duck17_sales$GEOID <- paste(duck17_sales$State.ANSI, duck17_sales$County.ANSI, sep = "")

duck17_sales$Value<- as.numeric(as.character(duck17_sales$Value))

duck17_sales$Value[is.na(duck17_sales$Value)] <- 0

duck17_sales <- duck17_sales %>%
  dplyr::select(GEOID, State, Value) %>%
  rename(sales = Value)

sum(duck17_sales$sales)
```


```{r}
duck <- merge(duck17_inven, duck17_sales, by = "GEOID", all = TRUE)
duck[is.na(duck)] <- 0

##------------------------------------------------------------------------- 
##calculate cattle on-feed as excreted 
duck <- duck %>%
  mutate(man_duck  =   (((inventory*1/6)+(sales/6*(6-1)/6))*(1/286)*56.304/10^9)) %>%
  dplyr::select(GEOID, man_duck)

sum(duck$man_duck)
```

## merge all CAFO manure 
```{r}
cattle <- merge(beef, milk17_pasture, by = "GEOID", all = TRUE)

cattlehog<- merge(cattle, hog, by = "GEOID", all = TRUE)

chicken <- merge(broiler, layer, by = "GEOID", all = TRUE)

chicken_pullet <- merge(chicken, pullet, by = "GEOID", all = TRUE)

turkey_duck <- merge(turkey, duck, by = "GEOID", all = TRUE)


cattlehog_chicken_pullet <- merge(cattlehog, chicken_pullet, by = "GEOID", all = TRUE)

all <- merge(cattlehog_chicken_pullet, turkey_duck, by = "GEOID", all = TRUE)

all[is.na(all)] <- 0



all <- all %>%
  mutate(total = man_beef + man_milk_withoutpas+ man_hog_P + man_broiler + man_layer + man_pullet + man_turkey + man_duck) %>%
  mutate(potential_recover = man_beef*0.7871*0.4 + man_milk_withoutpas*0.6844*0.4 + manhog_P_inven*0.8643*0.25 + manhog_P_sales*0.9550*0.25 + man_broiler*0.9800*0.6 + man_layer*0.95*0.69 + man_pullet*0.95*0.5 + man_turkey*0.8267*0.5 + 
           man_duck*0.695*0.5) %>%
  mutate(applied1=(0.83*man_beef)+  (0.28* man_milk_withoutpas) + (0.46*man_hog_P)+ 0.12*(man_broiler + man_layer +man_pullet +man_turkey))



all <- all %>%
  mutate(M1 = potential_recover - applied1) %>%
  mutate(M2 = total - potential_recover)

##-----------------------------------------make values of M1 <0 to 0 

##crop_manure$M1[crop_manure$M1 < 0] <- 0 
```


## read fertilizer data and calculate PUE
```{r}
fer17 <- read.csv("~/Desktop/pig/21 crops/farm_fer_17.csv")

fer17$GEOID[1:285]<- paste0("0", fer17$GEOID[1:285])

fer17 <- fer17 %>%
  mutate(ferton_n = farmfertN.kg.2017/10^6) %>%
  mutate(ferton_p = farmfertP.kg.2017/10^6) %>%
  mutate(fertg_p = ferton_p/10^3) %>%
  dplyr::select(GEOID, fertg_p)

## quantify M1, M2 

fer17$fertg_p[is.na(fer17$fertg_p)] <- 0
```




```{r}
## PUE

all <- merge(all, fer17, by = "GEOID", all = TRUE)

all[is.na(all)] <- 0

all <- all %>%
  mutate(crop21_current = fertg_p + applied1)
```



## 21 US common crop production

```{r}
hay17 <- read.csv("~/Desktop/pig/21 crops/hay2017.csv")

hay17 <- hay17 %>%
  dplyr::select(State.ANSI, County.ANSI, hay_tons)

hay17 <- hay17 %>%
    arrange(hay17$State.ANSI, decreasing = FALSE)

hay17$State.ANSI[1:286] <- paste0("0", hay17$State.ANSI[1:286])

hay17 <- hay17 %>%
    arrange(hay17$County.ANSI, decreasing = FALSE)

hay17$County.ANSI[1:237]<- paste0("00", hay17$County.ANSI[1:237])

hay17$County.ANSI[238:1873]<- paste0("0", hay17$County.ANSI[238:1873])

hay17$GEOID <- paste(hay17$State.ANSI, hay17$County.ANSI, sep = "")

hay17$hay_tons<- as.numeric(as.character(hay17$hay_tons))

hay17$hay_tons[is.na(hay17$hay_tons)] <- 0

hay17 <- hay17 %>%
  dplyr::select(GEOID, hay_tons)
```

```{r}
alfalfa17 <- read.csv("~/Desktop/pig/21 crops/alfalfa.csv")

alfalfa17 <- alfalfa17[1:2688, ]

alfalfa17 <- alfalfa17 %>%
  dplyr::select(State.ANSI, County.ANSI, alfalfa_tons)

alfalfa17 <- alfalfa17 %>%
    arrange(alfalfa17$State.ANSI, decreasing = FALSE)

alfalfa17$State.ANSI[1:210] <- paste0("0", alfalfa17$State.ANSI[1:210])

alfalfa17 <- alfalfa17 %>%
    arrange(alfalfa17$County.ANSI, decreasing = FALSE)

alfalfa17$County.ANSI[1:215]<- paste0("00", alfalfa17$County.ANSI[1:215])

alfalfa17$County.ANSI[216:1672]<- paste0("0", alfalfa17$County.ANSI[216:1672])

alfalfa17$GEOID <- paste(alfalfa17$State.ANSI, alfalfa17$County.ANSI, sep = "")

alfalfa17$alfalfa_tons<- as.numeric(as.character(alfalfa17$alfalfa_tons))

alfalfa17$alfalfa_tons[is.na(alfalfa17$alfalfa_tons)] <- 0

alfalfa17 <- alfalfa17 %>%
  dplyr::select(GEOID, alfalfa_tons)

```

```{r}
hayalfa <- merge(counties, hay17, by = "GEOID", all.x = TRUE)

hayalfab <- st_drop_geometry(hayalfa)

hayalfac <- merge(hayalfab, alfalfa17, by = "GEOID", all.x = TRUE)

hayalfac$hay_tons[is.na(hayalfac$hay_tons)] <- 0
hayalfac$alfalfa_tons[is.na(hayalfac$alfalfa_tons)] <- 0

hayalfac <- hayalfac %>%
  mutate(otherhay_tons = hay_tons - alfalfa_tons) %>%
  mutate(alfal_TgN = alfalfa_tons* 0.0056/10^6) %>%
  mutate(otherhay_TgN = otherhay_tons*0.003/10^6) %>%
  mutate(alfal_TgP1 = alfalfa_tons* 0.003/10^6) %>%
  mutate(otherhay_TgP1 = otherhay_tons*0.003/10^6)

##hayalfa <- merge(counties, hayalfa, by = "GEOID", all.x = TRUE)
```

```{r}
barley2017 <- read.csv("~/Desktop/pig/21 crops/barley.csv")

barley2017 <- barley2017[1:992, ]

barley2017 <- barley2017 %>%
  dplyr::select(State.ANSI, County.ANSI, barley_bushels)

barley2017 <- barley2017 %>%
    arrange(barley2017$State.ANSI, decreasing = FALSE)

barley2017$State.ANSI[1:66] <- paste0("0", barley2017$State.ANSI[1:66])

barley2017 <- barley2017 %>%
    arrange(barley2017$County.ANSI, decreasing = FALSE)

barley2017$County.ANSI[1:87]<- paste0("00", barley2017$County.ANSI[1:87])

barley2017$County.ANSI[88:720]<- paste0("0", barley2017$County.ANSI[88:720])

barley2017$GEOID <- paste(barley2017$State.ANSI, barley2017$County.ANSI, sep = "")

barley2017$barley_bushels <- as.numeric(as.character(barley2017$barley_bushels))

barley2017$barley_bushels[is.na(barley2017$barley_bushels)] <- 0

barley2017 <- barley2017 %>%
  dplyr::select(GEOID, barley_bushels)


barley2017 <- barley2017 %>%
  mutate(barley_TgN = barley_bushels* 0.0176* 21.772/10^9) %>%
  mutate(barley_TgP1 = barley_bushels* 0.0032* 21.772/10^9)
```

```{r}
corngrain17 <- read.csv("~/Desktop/pig/21 crops/corn_grain.csv")

corngrain17 <- corngrain17 %>%
  dplyr::select(State.ANSI, County.ANSI, corngrain_bu)

corngrain17 <- corngrain17 %>%
    arrange(corngrain17$State.ANSI, decreasing = FALSE)

corngrain17$State.ANSI[1:195] <- paste0("0", corngrain17$State.ANSI[1:195])

corngrain17 <- corngrain17 %>%
    arrange(corngrain17$County.ANSI, decreasing = FALSE)

corngrain17$County.ANSI[1:192]<- paste0("00", corngrain17$County.ANSI[1:192])

corngrain17$County.ANSI[193:1604]<- paste0("0", corngrain17$County.ANSI[193:1604])

corngrain17$GEOID <- paste(corngrain17$State.ANSI, corngrain17$County.ANSI, sep = "")

corngrain17$corngrain_bu <- as.numeric(as.character(corngrain17$corngrain_bu))

corngrain17$corngrain_bu[is.na(corngrain17$corngrain_bu)] <- 0

corngrain17 <- corngrain17 %>%
  dplyr::select(GEOID, corngrain_bu)


corngrain17 <- corngrain17 %>%
  mutate(corngrain_TgN = corngrain_bu* 0.0152* 25.4/10^9) %>%
  mutate(corngrain_TgP1 = corngrain_bu* 0.0034* 25.4/10^9)
```

```{r}
cornsilage17 <- read.csv("~/Desktop/pig/21 crops/corn_silage.csv")

cornsilage17 <- cornsilage17 %>%
  dplyr::select(State.ANSI, County.ANSI, corn_silage_tons)

cornsilage17 <- cornsilage17 %>%
    arrange(cornsilage17$State.ANSI, decreasing = FALSE)

cornsilage17$State.ANSI[1:128] <- paste0("0", cornsilage17$State.ANSI[1:128])

cornsilage17 <- cornsilage17 %>%
    arrange(cornsilage17$County.ANSI, decreasing = FALSE)

cornsilage17$County.ANSI[1:181]<- paste0("00", cornsilage17$County.ANSI[1:181])

cornsilage17$County.ANSI[182:1339]<- paste0("0", cornsilage17$County.ANSI[182:1339])

cornsilage17$GEOID <- paste(cornsilage17 $State.ANSI, cornsilage17$County.ANSI, sep = "")

cornsilage17$corn_silage_tons <- as.numeric(as.character(cornsilage17$corn_silage_tons))

cornsilage17$corn_silage_tons[is.na(cornsilage17$corn_silage_tons)] <- 0

cornsilage17 <- cornsilage17 %>%
  dplyr::select(GEOID, corn_silage_tons)

cornsilage17 <- cornsilage17 %>%
  mutate(corn_silage_TgN = corn_silage_tons* 0.002/10^6) %>%
  mutate(corn_silage_TgP1 = corn_silage_tons* 0.0008/10^6)
```

```{r}
cotton17 <- read.csv("~/Desktop/pig/21 crops/cotton.csv")

cotton17 <- cotton17 %>%
  dplyr::select(State.ANSI, County.ANSI, cotton_bales)

cotton17 <- cotton17 %>%
    arrange(cotton17$State.ANSI, decreasing = FALSE)

cotton17$State.ANSI[1:99] <- paste0("0", cotton17$State.ANSI[1:99])

cotton17 <- cotton17 %>%
    arrange(cotton17$County.ANSI, decreasing = FALSE)

cotton17$County.ANSI[1:32]<- paste0("00", cotton17$County.ANSI[1:32])

cotton17$County.ANSI[33:334]<- paste0("0", cotton17$County.ANSI[33:334])

cotton17$GEOID <- paste(cotton17$State.ANSI, cotton17$County.ANSI, sep = "")

cotton17$cotton_bales <- as.numeric(as.character(cotton17$cotton_bales))

cotton17$cotton_bales[is.na(cotton17$cotton_bales)] <- 0

cotton17 <- cotton17 %>%
  dplyr::select(GEOID, cotton_bales)

cotton17<- cotton17 %>%
  mutate(cotton_TgN = cotton_bales* 0.00088*0.21772/10^6) %>%
  mutate(cotton_TgP1 = cotton_bales* 0.011*0.21772/10^6)

```

```{r}
peanut17 <- read.csv("~/Desktop/pig/21 crops/peanut.csv")

peanut17 <- peanut17 %>%
  dplyr::select(State.ANSI, County.ANSI, peanut_lbs)

peanut17 <- peanut17 %>%
    arrange(peanut17$State.ANSI, decreasing = FALSE)

peanut17$State.ANSI[1:49] <- paste0("0", peanut17$State.ANSI[1:49])

peanut17 <- peanut17 %>%
    arrange(peanut17$County.ANSI, decreasing = FALSE)

peanut17$County.ANSI[1:17]<- paste0("00", peanut17$County.ANSI[1:17])

peanut17$County.ANSI[18:192]<- paste0("0", peanut17$County.ANSI[18:192])

peanut17$GEOID <- paste(peanut17$State.ANSI, peanut17$County.ANSI, sep = "")

peanut17$peanut_lbs <- as.numeric(as.character(peanut17$peanut_lbs))

peanut17$peanut_lbs[is.na(peanut17$peanut_lbs)] <- 0

peanut17 <- peanut17 %>%
  dplyr::select(GEOID, peanut_lbs)

peanut17<- peanut17 %>%
  mutate(peanut_TgN = peanut_lbs* 0.03888*0.453592/10^9) %>%
  mutate(peanut_TgP1 = peanut_lbs* 0.0046*0.453592/10^9)
```

```{r}

rice17 <- read.csv("~/Desktop/pig/21 crops/rice.csv")

rice17 <- rice17 %>%
  dplyr::select(State.ANSI, County.ANSI, rice_CWT)

rice17 <- rice17 %>%
    arrange(rice17$State.ANSI, decreasing = FALSE)

rice17$State.ANSI[1:52] <- paste0("0", rice17$State.ANSI[1:52])

rice17 <- rice17 %>%
    arrange(rice17$County.ANSI, decreasing = FALSE)

rice17$County.ANSI[1:7]<- paste0("00", rice17$County.ANSI[1:7])

rice17$County.ANSI[8:83]<- paste0("0", rice17$County.ANSI[8:83])

rice17$GEOID <- paste(rice17$State.ANSI,rice17$County.ANSI, sep = "")

rice17$rice_CWT <- as.numeric(as.character(rice17$rice_CWT))

rice17$rice_CWT[is.na(rice17$rice_CWT)] <- 0

rice17 <- rice17 %>%
  dplyr::select(GEOID, rice_CWT)

rice17<- rice17 %>%
  mutate(rice_TgN = rice_CWT* 0.016*50.8023/10^9) %>%
  mutate(rice_TgP1 = rice_CWT* 0.0028*50.8023/10^9)

```

```{r}
sorghum17 <- read.csv("~/Desktop/pig/21 crops/sorghum.csv")

sorghum17 <- sorghum17 %>%
  dplyr::select(State.ANSI, County.ANSI, sorghum_bu)

sorghum17  <- sorghum17  %>%
    arrange(sorghum17 $State.ANSI, decreasing = FALSE)

sorghum17$State.ANSI[1:86] <- paste0("0", sorghum17$State.ANSI[1:86])

sorghum17 <- sorghum17 %>%
    arrange(sorghum17$County.ANSI, decreasing = FALSE)

sorghum17$County.ANSI[1:66]<- paste0("00",sorghum17$County.ANSI[1:66])

sorghum17$County.ANSI[67:580]<- paste0("0", sorghum17$County.ANSI[67:580])

sorghum17$GEOID <- paste(sorghum17$State.ANSI,sorghum17$County.ANSI, sep = "")

sorghum17$sorghum_bu <- as.numeric(as.character(sorghum17$sorghum_bu))

sorghum17$sorghum_bu[is.na(sorghum17$sorghum_bu)] <- 0

sorghum17 <- sorghum17 %>%
  dplyr::select(GEOID, sorghum_bu)

sorghum17 <- sorghum17 %>%
  mutate(sorghum_TgN = sorghum_bu* 0.0161*25.4012/10^9) %>%
  mutate(sorghum_TgP1 = sorghum_bu* 0.0045*25.4012/10^9)
```

```{r}
tobacco17 <- read.csv("~/Desktop/pig/21 crops/tobacco.csv")

tobacco17 <- tobacco17 %>%
  dplyr::select(State.ANSI, County.ANSI, tobacco_lb)

tobacco17  <- tobacco17  %>%
    arrange(tobacco17$State.ANSI, decreasing = FALSE)

tobacco17$State.ANSI[1:2] <- paste0("0", tobacco17$State.ANSI[1:2])

tobacco17 <- tobacco17 %>%
    arrange(tobacco17$County.ANSI, decreasing = FALSE)

tobacco17$County.ANSI[1:17]<- paste0("00",tobacco17$County.ANSI[1:17])

tobacco17$County.ANSI[18:172]<- paste0("0", tobacco17$County.ANSI[18:172])

tobacco17$GEOID <- paste(tobacco17$State.ANSI,tobacco17$County.ANSI, sep = "")

tobacco17$tobacco_lb <- as.numeric(as.character(tobacco17$tobacco_lb))

tobacco17$tobacco_lb[is.na(tobacco17$tobacco_lb)] <- 0

tobacco17 <- tobacco17 %>%
  dplyr::select(GEOID, tobacco_lb)

tobacco17 <- tobacco17 %>%
  mutate(tobacco_TgN = tobacco_lb* 0.04*0.453592/10^9) %>%
  mutate(tobacco_TgP1 = tobacco_lb* 0.0066*0.453592/10^9)
```

```{r}
wheat17 <- read.csv("~/Desktop/pig/21 crops/wheat.csv")

wheat17 <- wheat17 %>%
  dplyr::select(State.ANSI, County.ANSI, wheat_bu)

wheat17 <- wheat17  %>%
    arrange(wheat17$State.ANSI, decreasing = FALSE)

wheat17$State.ANSI[1:198] <- paste0("0", wheat17$State.ANSI[1:198])

wheat17 <- wheat17 %>%
    arrange(wheat17$County.ANSI, decreasing = FALSE)

wheat17$County.ANSI[1:166]<- paste0("00",wheat17$County.ANSI[1:166])

wheat17$County.ANSI[167:1440]<- paste0("0", wheat17$County.ANSI[167:1440])

wheat17$GEOID <- paste(wheat17$State.ANSI,wheat17$County.ANSI, sep = "")

wheat17$wheat_bu <- as.numeric(as.character(wheat17$wheat_bu))

wheat17$wheat_bu[is.na(wheat17$wheat_bu)] <- 0

wheat17 <- wheat17 %>%
  dplyr::select(GEOID, wheat_bu, State.ANSI)

wheat17s <- wheat17 %>%
  filter(State.ANSI %in% c("27", "30", "38", "56")) 

wheat17s <- wheat17s %>%
  mutate(wheat_TgP1 = wheat_bu*  0.0042*27.216/10^9)

wheat17o <- wheat17 %>%
  filter(!State.ANSI %in% c("27", "30", "38", "56")) 

wheat17o <- wheat17o %>%
  mutate(wheat_TgP1 = wheat_bu* 0.0042*27.216/10^9)

wheat17t <- rbind(wheat17o, wheat17s)


wheat17 <- wheat17t %>%
  mutate(wheat_TgN = wheat_bu* 0.01952*27.216/10^9) 

```

```{r}
sunflower17 <- read.csv("~/Desktop/pig/21 crops/sunflower.csv")

sunflower17 <- sunflower17 %>%
  dplyr::select(State.ANSI, County.ANSI, sunflower_lbs)

sunflower17 <- sunflower17  %>%
    arrange(sunflower17$State.ANSI, decreasing = FALSE)

sunflower17$State.ANSI[1:47] <- paste0("0", sunflower17$State.ANSI[1:47])

sunflower17 <-sunflower17 %>%
    arrange(sunflower17$County.ANSI, decreasing = FALSE)

sunflower17$County.ANSI[1:46]<- paste0("00",sunflower17$County.ANSI[1:46])

sunflower17$County.ANSI[47:357]<- paste0("0", sunflower17$County.ANSI[47:357])

sunflower17$GEOID <- paste(sunflower17$State.ANSI,sunflower17$County.ANSI, sep = "")

sunflower17$sunflower_lbs <- as.numeric(as.character(sunflower17$sunflower_lbs))

sunflower17$sunflower_lbs[is.na(sunflower17$sunflower_lbs)] <- 0

sunflower17 <- sunflower17 %>%
  dplyr::select(GEOID, sunflower_lbs)

sunflower17 <- sunflower17 %>%
  mutate(sunflower_TgN = sunflower_lbs* 0.01968*0.453592/10^9) %>%
  mutate(sunflower_TgP1 = sunflower_lbs* 0.0039*0.453592/10^9)
```

```{r}
sugarcane17 <- read.csv("~/Desktop/pig/21 crops/sugarcane2.csv")

sugarcane17 <- sugarcane17 %>%
  dplyr::select(State.ANSI, County.ANSI, sugarcane_tons)

sugarcane17 <- sugarcane17  %>%
    arrange(sugarcane17$State.ANSI, decreasing = FALSE)

sugarcane17 <-sugarcane17 %>%
    arrange(sugarcane17$County.ANSI, decreasing = FALSE)

sugarcane17$County.ANSI[1:8]<- paste0("00",sugarcane17$County.ANSI[1:8])

sugarcane17$County.ANSI[9:33]<- paste0("0", sugarcane17$County.ANSI[9:33])

sugarcane17$GEOID <- paste(sugarcane17$State.ANSI,sugarcane17$County.ANSI, sep = "")

sugarcane17$sugarcane_tons <- as.numeric(as.character(sugarcane17$sugarcane_tons))

sugarcane17$sugarcane_tons[is.na(sugarcane17$sugarcane_tons)] <- 0

sugarcane17 <- sugarcane17 %>%
  dplyr::select(GEOID, sugarcane_tons)

sugarcane17 <- sugarcane17 %>%
  mutate(sugarcane_TgN = sugarcane_tons* 0.00032/10^6) %>%
  mutate(sugarcane_TgP1 = sugarcane_tons* 0.0003/10^6)
```

```{r}
sugarbeet17 <- read.csv("~/Desktop/pig/21 crops/sugarbeet.csv")

sugarbeet17 <- sugarbeet17 %>%
  dplyr::select(State.ANSI, County.ANSI, sugarbeet_tons)

sugarbeet17 <- sugarbeet17  %>%
    arrange(sugarbeet17$State.ANSI, decreasing = FALSE)

sugarbeet17$State.ANSI[1:13] <- paste0("0", sugarbeet17$State.ANSI[1:13])

sugarbeet17 <-sugarbeet17 %>%
    arrange(sugarbeet17$County.ANSI, decreasing = FALSE)

sugarbeet17$County.ANSI[1:10]<- paste0("00",sugarbeet17$County.ANSI[1:10])

sugarbeet17$County.ANSI[11:89]<- paste0("0", sugarbeet17$County.ANSI[11:89])

sugarbeet17$GEOID <- paste(sugarbeet17$State.ANSI,sugarbeet17$County.ANSI, sep = "")

sugarbeet17$sugarbeet_tons <- as.numeric(as.character(sugarbeet17$sugarbeet_tons))

sugarbeet17$sugarbeet_tons[is.na(sugarbeet17$sugarbeet_tons)] <- 0

sugarbeet17 <- sugarbeet17 %>%
  dplyr::select(GEOID, sugarbeet_tons)

sugarbeet17 <- sugarbeet17 %>%
  mutate(sugarbeet_TgN = sugarbeet_tons* 0.00208/10^6) %>%
  mutate(sugarbeet_TgP1 = sugarbeet_tons* 0.0005/10^6)
```

```{r}
soybean17 <- read.csv("~/Desktop/pig/21 crops/soybeans.csv")

soybean17 <- soybean17[1:2200, ]

soybean17 <- soybean17 %>%
  dplyr::select(State.ANSI, County.ANSI, soybean_bushels)

soybean17<- soybean17  %>%
    arrange(soybean17$State.ANSI, decreasing = FALSE)

soybean17$State.ANSI[1:134] <- paste0("0", soybean17$State.ANSI[1:134])

soybean17 <-soybean17 %>%
    arrange(soybean17$County.ANSI, decreasing = FALSE)

soybean17$County.ANSI[1:153]<- paste0("00",soybean17$County.ANSI[1:153])

soybean17$County.ANSI[154:1284]<- paste0("0", soybean17$County.ANSI[154:1284])

soybean17$GEOID <- paste(soybean17$State.ANSI,soybean17$County.ANSI, sep = "")

soybean17$soybean_bushels <- as.numeric(as.character(soybean17$soybean_bushels))

soybean17$soybean_bushels[is.na(soybean17$soybean_bushels)] <- 0

soybean17 <- soybean17 %>%
  dplyr::select(GEOID, soybean_bushels)

soybean17 <- soybean17 %>%
  mutate(soybean_TgN = soybean_bushels* 27.2155*0.06088/10^9) %>%
  mutate(soybean_TgP1 = soybean_bushels* 27.2155*0.0081/10^9)

```

```{r}
canola17 <- read.csv("~/Desktop/pig/21 crops/canola.csv")

canola17 <- canola17 %>%
  dplyr::select(State.ANSI, County.ANSI, canola_lbs)

canola17<- canola17  %>%
    arrange(canola17$State.ANSI, decreasing = FALSE)

canola17$State.ANSI[1:10] <- paste0("0", canola17$State.ANSI[1:10])

canola17 <-canola17 %>%
    arrange(canola17$County.ANSI, decreasing = FALSE)

canola17$County.ANSI[1:21]<- paste0("00",canola17$County.ANSI[1:21])

canola17$County.ANSI[22:193]<- paste0("0", canola17$County.ANSI[22:193])

canola17$GEOID <- paste(canola17$State.ANSI,canola17$County.ANSI, sep = "")

canola17$canola_lbs <- as.numeric(as.character(canola17$canola_lbs))

canola17$canola_lbs[is.na(canola17$canola_lbs)] <- 0

canola17 <- canola17 %>%
  dplyr::select(GEOID, canola_lbs)

canola17 <- canola17 %>%
  mutate(canola_TgN = canola_lbs* 0.453592*0.03136/10^9) %>%
  mutate(canola_TgP1 = canola_lbs* 0.453592*0.0029/10^9)

```

```{r}
drybeans17 <- read.csv("~/Desktop/pig/21 crops/drybeans_2017.csv")

drybeans17 <- drybeans17 %>%
  dplyr::select(State.ANSI, County.ANSI, beans_dry_cwt)

drybeans17 <- drybeans17  %>%
    arrange(drybeans17$State.ANSI, decreasing = FALSE)

drybeans17$State.ANSI[1:66] <- paste0("0", drybeans17$State.ANSI[1:66])

drybeans17 <- drybeans17 %>%
    arrange(drybeans17$County.ANSI, decreasing = FALSE)

drybeans17$County.ANSI[1:42]<- paste0("00",drybeans17$County.ANSI[1:42])

drybeans17$County.ANSI[43:320]<- paste0("0", drybeans17$County.ANSI[43:320])

drybeans17$GEOID <- paste(drybeans17$State.ANSI,drybeans17$County.ANSI, sep = "")

drybeans17$beans_dry_cwt <- as.numeric(as.character(drybeans17$beans_dry_cwt))

drybeans17$beans_dry_cwt[is.na(drybeans17$beans_dry_cwt)] <- 0

drybeans17 <- drybeans17 %>%
  dplyr::select(GEOID, beans_dry_cwt)

drybeans17 <- drybeans17 %>%
  mutate(drybeans_TgN = beans_dry_cwt/19.684/10^6* 0.0446) %>%
  mutate(drybeans_TgP1 = beans_dry_cwt/19.684/10^6* 0.0057)
```


```{r}
NUdata <- read.csv("~/Desktop/NUGIS data/NuGIS_County_Data.csv")

NUdata16 <- NUdata %>%
  filter(year == "2016") %>%
  dplyr::select(year, state, county, FIPS,Total_Harvested_Cropland_Acres) ## filter year in 2016

NUdata16$FIPS[1:285] <- paste0("0", NUdata16$FIPS[1:285])

names(NUdata16)[names(NUdata16) == "FIPS"] <- "GEOID"

NUdata16 <- NUdata16 %>%
  mutate(potatoes_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*20.45343*0.00256) %>%
  mutate(potatoes_TgP1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*20.45343*0.001)

NUdata16 <- NUdata16 %>%
  mutate(apples_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*5.24067*0.0005) %>%
  mutate(apples_TgP1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*5.24067*0.0007)

NUdata16 <- NUdata16 %>%
  mutate(oranges_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*4.61576*0.0018) %>%
  mutate(oranges_TgP1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*4.61576*0.0004)

NUdata16 <- NUdata16 %>%
  mutate(sweetcorn_TgN = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*3.846000031*0.00288) %>%
  mutate(sweetcorn_TgP1 = Total_Harvested_Cropland_Acres/sum(Total_Harvested_Cropland_Acres, na.rm = TRUE)*3.846000031*0.0004)



```


```{r}
hb <- merge(hayalfac, barley2017, by = "GEOID", all = TRUE)

grainsilage <- merge(corngrain17, cornsilage17, by = "GEOID", all = TRUE)

hbcorn <- merge(hb, grainsilage, by = "GEOID", all = TRUE)

cp <- merge(cotton17, peanut17, by = "GEOID", all = TRUE)

rs <- merge(rice17, sorghum17, by = "GEOID", all = TRUE)

cprs <- merge(cp, rs, by = "GEOID", all = TRUE)

hbcorncprs <- merge(hbcorn,cprs, by = "GEOID", all = TRUE )

tw <- merge(tobacco17, wheat17, by = "GEOID", all = TRUE)

ss <- merge(sunflower17, sugarcane17, by = "GEOID", all = TRUE)

ss2 <- merge(sugarbeet17, soybean17, by = "GEOID", all = TRUE)

twss <- merge(tw,ss, by = "GEOID", all = TRUE )

twss2 <- merge(twss, ss2, by = "GEOID", all = TRUE)

hbcotncprstwss2 <- merge(hbcorncprs, twss2, by =  "GEOID", all = TRUE)

hbcotncprstwss2 <- merge(hbcotncprstwss2, canola17, by = "GEOID", all = TRUE)

hbcotncprstwss3 <- merge(hbcotncprstwss2, drybeans17, by = "GEOID", all = TRUE)

hbcotncprstwss3 <- merge(counties, hbcotncprstwss3, by = "GEOID", all.x = TRUE )

##hbcotncprstwss3_new <- hbcotncprstwss3[!duplicated(hbcotncprstwss3[ ,"GEOID", ]),]  # Delete rows



hbcotncprstwss3[is.na(hbcotncprstwss3)] <- 0

hbcotncprstwss3_newdp <- st_drop_geometry(hbcotncprstwss3)

crop17 <- merge(NUdata16,hbcotncprstwss3_newdp, by = "GEOID", all.y = TRUE )

crop17[is.na(crop17)] <- 0

crop17 <- crop17 %>%
  mutate(crop21pro = alfal_TgP1 + otherhay_TgP1 + barley_TgP1 + corngrain_TgP1 + corn_silage_TgP1 + cotton_TgP1 + peanut_TgP1 + rice_TgP1 + sorghum_TgP1 +tobacco_TgP1 +wheat_TgP1 +  sunflower_TgP1 + sugarcane_TgP1 +  sugarbeet_TgP1 +soybean_TgP1 +  drybeans_TgP1 + apples_TgP1 + oranges_TgP1 + potatoes_TgP1 + sweetcorn_TgP1 + canola_TgP1) %>%
  dplyr::select(GEOID, crop21pro)

```



```{r}
##crop17 %>%
  ##filter(GEOID == "08014")
```


```{r}
all <- merge(all, crop17, by = "GEOID", all = TRUE)


all <- all %>%
  mutate(PUE = crop21pro/(fertg_p + applied1))
```



```{r}
counties <- st_read("~/Desktop/NUGIS data/data/cb_2018_us_county_500k/cb_2018_us_county_500k.shp")

counties <- counties %>%
  filter(STATEFP %in% c("01", "05", "04", "06", "08", "09", "10", "12", "13", "19", "16", "17",
                        "18", "20", "21", "22", "25", "24", "23", "26", "27", "29", "28",
                        "30", "37", "38", "31", "33", "34", "35", "32", "36", "39", "40",
                        "41", "42", "44", "45", "46", "47", "48", "49", "51", "50", "53", "55",
                        "54", "56")) 

## plot(st_geometry(counties))

counties<- st_transform(counties, CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"))
```

```{r}
library(dplyr)

all <- st_drop_geometry(all)

all <- merge(counties, all, by = "GEOID", all.x = TRUE)

all$PUE[!is.finite(all$PUE)] <- NA

tm_shape(all) +
  tm_fill("PUE",title="PUE", breaks = c(0, 0.6, 0.8, 1, 15), labels = c("0-0.6", "0.6-0.8", "0.8-1", ">1"), palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
```

```{r}
all <- all %>%
  mutate(current_P_balance = -fertg_p )


tm_shape(all) +
  tm_fill("current_P_balance",title="current manure P balance", style = "quantile", palette=pal7, colorNA = "white", textNA = "NA")  +
  tm_borders() +
  tm_layout( title.position = c("right","top"), title = "",legend.text.size = 1.1, legend.title.size = 1.2, legend.title.fontface = 2,frame = FALSE) 
```


```{r}

all <- all %>%
  rename(cropP = crop21pro) 


Pdata <- all %>%
  dplyr::select(GEOID, PUE, cropP, fertg_p, current_P_balance)

Pdata <- st_drop_geometry(Pdata)

write.csv(Pdata, "~/Desktop/revised manure sur/S_revision/Pdata.csv")

```













































































































































